## Функция потерь с L1 и L2 регуляризацией

Подумайте, как изменится алгоритм поиска решения для линейной модели, если добавить регуляризацию L1 и L2 к функции потерь. Предоставьте ответ в своём проекте:

**Функция потерь:**

$$
L(w) = \frac{1}{n} \|y - (Xw + b)\|^2 + \lambda_1 \|w\|_1 + \frac{\lambda_2}{2} \|w\|_2^2
$$

**Обновление весов при градиентном спуске:**

$$
w \leftarrow w - \eta \left( \frac{2}{n} X^T (Xw + b - y) + \lambda_2 w + \lambda_1 \cdot \text{sign}(w) \right)
$$

$$
b \leftarrow b - \eta \left( \frac{2}{n}(Xw + b - y) \right)
$$

где:
- $L(w)$ - функция потерь
- $w$ - вектор весов
- $X$ - матрица признаков
- $y$ - вектор целевых значений
- $n$ - количество признаковов
- $\lambda_1$ - коэффициент L1-регуляризации
- $\lambda_2$ - коэффициент L2-регуляризации
- $\eta$ - скорость обучения
- $\text{sign}(w)$ - поэлементная функция знака

## 1) Ответь на вопросы

### Получите аналитическое решение задачи регрессии, используя векторную форму уравнения.

**Функция потерь MSE**:  
$$\mathcal{L}(w) = \frac{1}{n} \|y - Xw\|_2^2$$

**Градиент функции**:  
$$\nabla_w \mathcal{L}(w) = -\frac{2}{n} X^T (y - Xw)$$

**Условие минимума**:  
$$X^T (y - Xw) = 0$$

**Аналитическое решение**:  
$$w = (X^T X)^{-1} X^T y$$

**Особенности**:  
- Решение существует, если $X^T X$ обратима  
- При вырожденной матрице используют псевдообратную матрицу  
- Смещение (intercept) включается как дополнительный признак со значением 1

### Что меняется в решении при добавлении регуляризаций L1 и L2 к функции потерь?


**1. L2-регуляризация (Ridge Regression)**
**Функция потерь**:  
$$\mathcal{L}_{L2}(w) = \frac{1}{n} \|y - Xw\|_2^2 + \lambda \|w\|_2^2$$

**Решение**:  
$$w = (X^T X + \lambda I)^{-1} X^T y$$

**Эффекты**:  
- Стабилизация обращения матрицы  
- Уменьшение величины весов  
- Снижение влияния мультиколлинеарности  

**2. L1-регуляризация (Lasso Regression)**
**Функция потерь**:  
$$\mathcal{L}_{L1}(w) = \frac{1}{n} \|y - Xw\|_2^2 + \lambda \|w\|_1$$

**Решение**:  
Не имеет аналитической формы, решается численными методами



**Компактная запись через soft-thresholding** \
**Решение для каждого веса**:
$$w_j = S_{\frac{n\lambda}{2}} \left( w_j^{OLS} - \sum_{k \neq j} X_j^T X_k w_k \right)$$


*Функция потерь OLS*:
$$\mathcal{L}_{OLS}(w) = \frac{1}{n} \|y - Xw\|_2^2$$

*Аналитическое решение*:
$$w^{OLS} = (X^T X)^{-1} X^T y$$

**где soft-thresholding оператор**:
$$S_{\kappa}(a) = \text{sign}(a) \cdot \max(0, |a| - \kappa)$$

**В координатном спуске**:
$$w_j = \frac{1}{\|X_j\|^2} S_{\frac{n\lambda}{2}} \left( X_j^T(y - X_{-j}w_{-j}) \right)$$

**Практическая интерпретация**

**Пороговое правило**:
- Если $|X_j^T(y - Xw)| > \frac{n\lambda}{2}$: вес ненулевой
- Если $|X_j^T(y - Xw)| \leq \frac{n\lambda}{2}$: вес обнуляется

**Это объясняет**:
- Почему L1 создает разреженность
- Как λ контролирует количество ненулевых весов
- Почему коррелированные признаки могут "конкурировать" за включение в модель

### Объясните, почему для отбора признаков часто используется регуляризация L1. Почему после подгонки модели многие веса оказываются равными 0?


**Почему веса обнуляются**\
**Геометрическая интерпретация**:  
- L1-ограничение образует гиперкуб в пространстве весов  
- Оптимум часто достигается в углах гиперкуба, где координаты равны нулю

**Математическое объяснение**:  
- Субградиент условия оптимальности:  
  $$\frac{\partial \mathcal{L}}{\partial w_i} + \lambda \cdot \text{sign}(w_i) = 0$$
- Если влияние признака мало: $\left|\frac{\partial \mathcal{L}}{\partial w_i}\right| < \lambda$, то вес обнуляется

 *Особенно полезно при большом количестве признаков*

## 2) Введение — выполните всю предобработку из предыдущего урока

In [12]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures, MinMaxScaler, StandardScaler
from sklearn.linear_model import LinearRegression, SGDRegressor, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from sklearn.dummy import DummyRegressor
from sklearn.tree import DecisionTreeRegressor
from collections import Counter
from tqdm import tqdm

In [13]:
train_df = pd.read_json("./data/train.json")
train_df

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address,interest_level
4,1.0,1,8579a0b0d54db803821a35a4a615e97a,2016-06-16 05:55:27,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"[Dining Room, Pre-War, Laundry in Building, Di...",40.7108,7170325,-73.9539,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/7170325_3bb5ac84...,2400,145 Borinquen Place,medium
6,1.0,2,b8e75fc949a6cd8225b455648a951712,2016-06-01 05:44:33,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"[Doorman, Elevator, Laundry in Building, Dishw...",40.7513,7092344,-73.9722,955db33477af4f40004820b4aed804a0,[https://photos.renthop.com/2/7092344_7663c19a...,3800,230 East 44th,low
9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,2016-06-14 15:19:59,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"[Doorman, Elevator, Laundry in Building, Laund...",40.7575,7158677,-73.9625,c8b10a317b766204f08e613cef4ce7a0,[https://photos.renthop.com/2/7158677_c897a134...,3495,405 East 56th Street,medium
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,[https://photos.renthop.com/2/7211212_1ed4542e...,3000,792 Metropolitan Avenue,medium
15,1.0,0,bfb9405149bfff42a92980b594c28234,2016-06-28 03:50:23,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"[Doorman, Elevator, Fitness Center, Laundry in...",40.7439,7225292,-73.9743,2c3b41f588fbb5234d8a1e885a436cfa,[https://photos.renthop.com/2/7225292_901f1984...,2795,340 East 34th Street,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124000,1.0,3,92bbbf38baadfde0576fc496bd41749c,2016-04-05 03:58:33,There is 700 square feet of recently renovated...,W 171 Street,"[Elevator, Dishwasher, Hardwood Floors]",40.8433,6824800,-73.9396,a61e21da3ba18c7a3d54cfdcc247e1f8,[https://photos.renthop.com/2/6824800_0682be16...,2800,620 W 171 Street,low
124002,1.0,2,5565db9b7cba3603834c4aa6f2950960,2016-04-02 02:25:31,"2 bedroom apartment with updated kitchen, rece...",Broadway,"[Common Outdoor Space, Cats Allowed, Dogs Allo...",40.8198,6813268,-73.9578,8f90e5e10e8a2d7cf997f016d89230eb,[https://photos.renthop.com/2/6813268_1e6fcc32...,2395,3333 Broadway,medium
124004,1.0,1,67997a128056ee1ed7d046bbb856e3c7,2016-04-26 05:42:03,No Brokers Fee * Never Lived 1 Bedroom 1 Bathr...,210 Brighton 15th St,"[Dining Room, Elevator, Pre-War, Laundry in Bu...",40.5765,6927093,-73.9554,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/6927093_93a52104...,1850,210 Brighton 15th St,medium
124008,1.0,2,3c0574a740154806c18bdf1fddd3d966,2016-04-19 02:47:33,Wonderful Bright Chelsea 2 Bedroom apartment o...,West 21st Street,"[Pre-War, Laundry in Unit, Dishwasher, No Fee,...",40.7448,6892816,-74.0017,c3cd45f4381ac371507090e9ffabea80,[https://photos.renthop.com/2/6892816_1a8d087a...,4195,350 West 21st Street,medium
124009,1.0,3,d89f514c3ed0abaae52cba7017ac0701,2016-04-20 05:34:00,***PRIME MIDTOWN EAST OFF PARK AVE***TRUE 3 BE...,E 54th St,"[Dining Room, Elevator, Laundry in Building, D...",40.7594,6901023,-73.9712,e90f2ded843cdb2efd65ef47d9fc8029,[https://photos.renthop.com/2/6901023_02052d90...,4280,123 E 54th St,high

In [16]:
test_df = pd.read_json("./data/test.json")
test_df

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address
0,1.0,1,79780be1514f645d7e6be99a3de696c5,2016-06-11 05:29:41,Large with awesome terrace--accessible via bed...,Suffolk Street,"[Elevator, Laundry in Building, Laundry in Uni...",40.7185,7142618,-73.9865,b1b1852c416d78d7765d746cb1b8921f,[https://photos.renthop.com/2/7142618_1c45a2c8...,2950,99 Suffolk Street
1,1.0,2,0,2016-06-24 06:36:34,Prime Soho - between Bleecker and Houston - Ne...,Thompson Street,"[Pre-War, Dogs Allowed, Cats Allowed]",40.7278,7210040,-74.0000,d0b5648017832b2427eeb9956d966a14,[https://photos.renthop.com/2/7210040_d824cc71...,2850,176 Thompson Street
2,1.0,0,0,2016-06-17 01:23:39,Spacious studio in Prime Location. Cleanbuildi...,Sullivan Street,"[Pre-War, Dogs Allowed, Cats Allowed]",40.7260,7174566,-74.0026,e6472c7237327dd3903b3d6f6a94515a,[https://photos.renthop.com/2/7174566_ba3a35c5...,2295,115 Sullivan Street
3,1.0,2,f9c826104b91d868e69bd25746448c0c,2016-06-21 05:06:02,For immediate access call Bryan.<br /><br />Bo...,Jones Street,"[Hardwood Floors, Dogs Allowed, Cats Allowed]",40.7321,7191391,-74.0028,41735645e0f8f13993c42894023f8e58,[https://photos.renthop.com/2/7191391_8c2f2d49...,2900,23 Jones Street
5,1.0,1,81062936e12ee5fa6cd2b965698e17d5,2016-06-16 07:24:27,Beautiful TRUE 1 bedroom in a luxury building ...,Exchange Place,"[Roof Deck, Doorman, Elevator, Fitness Center,...",40.7054,7171695,-74.0095,a742cf7dd3b2627d83417bc3a1b3ec96,[https://photos.renthop.com/2/7171695_089ffee2...,3254,20 Exchange Place
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124003,1.0,1,bd863d28a6b119ac3bc72d5f27b07f24,2016-04-26 16:09:55,BRAND NEW TO MARKET 1BDR \r107TH AND LEXINGTON...,150 EAST 107TH STREET,[],40.7925,6928108,-73.9454,453d46f8113e1f2c730c2ee5a4469c71,[https://photos.renthop.com/2/6928108_231eb983...,1700,158 EAST 107TH STREET
124005,1.0,2,9174b75c0cd978eb0e5aa93afbad754b,2016-04-21 05:06:19,Convertible 2BR apartment features a brand new...,E 33rd St.,"[Doorman, Elevator, Laundry in Building, Dishw...",40.7456,6906674,-73.9797,2983e45f7e0ad87d677dacd13e362785,[https://photos.renthop.com/2/6906674_9fe899a8...,4195,141 E 33rd St.
124006,1.0,0,0,2016-04-20 01:31:52,"Let's get you in to see this $2,400/mo, recent...",Lexington Avenue,"[Dogs Allowed, Cats Allowed]",40.7416,6897967,-73.9829,e6472c7237327dd3903b3d6f6a94515a,[],2400,95 Lexington Avenue
124007,2.0,2,c90c010e5505365676538e64d02aa1e0,2016-04-08 02:26:45,CooperCooper.com :: Web ID #171357; Access 100...,Park Avenue,"[Doorman, Elevator, Cats Allowed, Dogs Allowed]",40.7485,6842183,-73.9800,6e5c10246156ae5bdcd9b487ca99d96a,[https://photos.renthop.com/2/6842183_b1fe51f4...,6895,41 Park Avenue
124010,1.0,3,1a6cf9b71da65cdc0cfd5015a75317ac,2016-04-18 02:51:21,New renovated Bright 3Br Murray Hill. 3 QUEEN ...,E 35 Street,"[Garden/Patio, Laundry in Unit, Dishwasher, Ha...",40.7447,6889319,-73.9741,d9039c43983f6e564b1482b273bd7b01,[https://photos.renthop.com/2/6889319_79f186e7...,4695,326 E 35 Street

In [17]:
train_df = train_df[["bathrooms", "bedrooms", "features", "price"]]
test_df = test_df[["bathrooms", "bedrooms", "features", "price"]]

In [32]:
quantile_1 = train_df["price"].quantile(0.01)
quantile_99 = train_df["price"].quantile(0.99)

train_df = train_df[(train_df["price"] > quantile_1) & (train_df["price"] < quantile_99)]
test_df = test_df[(test_df["price"] > quantile_1) & (test_df["price"] < quantile_99)]

In [34]:
train_df.head()

,bathrooms,bedrooms,features,price
4,1.0,1,"[Dining Room, Pre-War, Laundry in Building, Di...",2400
6,1.0,2,"[Doorman, Elevator, Laundry in Building, Dishw...",3800
9,1.0,2,"[Doorman, Elevator, Laundry in Building, Laund...",3495
10,1.5,3,[],3000
15,1.0,0,"[Doorman, Elevator, Fitness Center, Laundry in...",2795

In [38]:
test_df.head()

,bathrooms,bedrooms,features,price
0,1.0,1,"[Elevator, Laundry in Building, Laundry in Uni...",2950
1,1.0,2,"[Pre-War, Dogs Allowed, Cats Allowed]",2850
2,1.0,0,"[Pre-War, Dogs Allowed, Cats Allowed]",2295
3,1.0,2,"[Hardwood Floors, Dogs Allowed, Cats Allowed]",2900
5,1.0,1,"[Roof Deck, Doorman, Elevator, Fitness Center,...",3254

## 3) Введение в анализ данных, часть 2

### Удалите неиспользуемые символы ([,], ', " и пробел) из столбца.

их нет...
там просто list...

In [43]:
type(test_df["features"][0])

list

In [44]:
# f = lambda x: [s.strip() for s in (x[1:-1]).split(",")]
# test_df["features"].map(f)
# train_df["features"].map(f)
# del(f)

### Получить все значения из каждого списка и объединить результаты в один большой список для всего набора данных. Для этого можно использовать DataFrame.iterrows().

In [46]:
all_features_test = [item for sublist in test_df["features"] for item in sublist]
all_features_train = [item for sublist in train_df["features"] for item in sublist]

In [50]:
all_features_test

['Elevator',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'Outdoor Space',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Pre-War',
 'Laundry in Building',
 'High Speed Internet',
 'Wheelchair Access',
 'Dogs Allowed',
 'Cats Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'No Fee',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry In Building',
 'Swimming Pool',
 'Roof Deck',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Hardwood Floors',
 'No Fee',
 'No Fee',
 'Fitness Center',
 'Cats Allowed',
 'Dogs Allowed',
 'Swimming Pool',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Pre-War',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Dishwasher',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Elevator',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Cats Allowed',
 'Exclusive',
 'Hardwood',
 'High Ceilings',
 'Marble Bath',
 'Granite Kitchen',
 'Light',
 'Eat In Kitchen',
 'Swimming Pool',
 'Roof Deck',
 'Balcony',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Terrace',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Doorman',
 'No Fee',
 'Cats Allowed',
 'Hardwood Floors',
 'Elevator',
 'Dogs Allowed',
 'Dishwasher',
 'Laundry in Building',
 'Pre-War',
 'Swimming Pool',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'High Speed Internet',
 'Roof Deck',
 'Dining Room',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Loft',
 'Pre-War',
 'Laundry in Building',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Pre-War',
 'Fireplace',
 'Elevator',
 'Furnished',
 'Hardwood Floors',
 'Dishwasher',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Elevator',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Newly renovated',
 'Cats Allowed',
 'Dogs Allowed',
 'Doorman',
 'Elevator',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Pets on approval',
 'Pre-War',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'Washer in Unit',
 'Dryer in Unit',
 'Dishwasher',
 'No Fee',
 'Cats Allowed',
 'Dogs Allowed',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Loft',
 'Laundry in Building',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Elevator',
 'Pre-War',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Elevator',
 'Pre-War',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Doorman',
 'Fitness Center',
 'Pool',
 'Elevator',
 'Laundry in Unit',
 'Dishwasher',
 'Cats Allowed',
 'Dogs Allowed',
 'Garage',
 'Cats Allowed',
 'Dogs Allowed',
 'Laundry In Building',
 'Stainless Steel appliances',
 'Large windows',
 'High   ceilings',
 'Hardwood Floors',
 'Great Veiws',
 'Stainless Steel   Appliances',
 'Eat In Kitchen',
 'Dishwasher',
 'Hardwood   floors',
 'High Ceilings',
 'All pets ok',
 'Hardwood Floors',
 'DISHWASHER',
 'RENOVATED',
 'HARDWOOD FLOORS',
 'Elevator',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Dining Room',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Laundry in Unit',
 'Hardwood Floors',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Fitness Center',
 'Elevator',
 'Garage',
 'Roof-deck',
 'Laundry Room',
 'Cats Allowed',
 'Dogs Allowed',
 'Dishwasher',
 'Hardwood',
 'High Ceilings',
 'Renovated',
 'Marble Bath',
 'Granite Kitchen',
 'Light',
 'Elevator',
 'Dogs Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'Cats Allowed',
 'Dining Room',
 'Garden/Patio',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Dining Room',
 'Doorman',
 'Fitness Center',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Doorman',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Doorman',
 'Pre-War',
 'elevator',
 'Cats Allowed',
 'Private Outdoor Space',
 'Dogs Allowed',
 'Reduced Fee',
 'Pre-War',
 'Elevator',
 'Laundry in Building',
 'Swimming Pool',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Laundry in Unit',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'New Construction',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'No Fee',
 'Elevator',
 'Doorman',
 'Elevator',
 'Dogs Allowed',
 'Cats Allowed',
 'Loft',
 'Hardwood Floors',
 'Cats Allowed',
 'Dogs Allowed',
 'No Fee',
 'Elevator',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'Dining Room',
 'Elevator',
 'Garden/Patio',
 'Multi-Level',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'New Construction',
 'Dogs Allowed',
 'Cats Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'Doorman',
 'Fitness Center',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Dining Room',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Pre-War',
 'Laundry in Building',
 'Laundry in Unit',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Pre-War',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'New Construction',
 'Hardwood Floors',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Pre-War',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Balcony',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Dishwasher',
 'No Fee',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Common Outdoor Space',
 'Laundry In Unit',
 'Cats Allowed',
 'Dogs Allowed',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry In Building',
 'Doorman',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Doorman',
 'Doorman',
 'Elevator',
 'Dishwasher',
 'Hardwood Floors',
 'Pre-War',
 'Hardwood Floors',
 'Garden/Patio',
 'Pre-War',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'Outdoor Space',
 'Cats Allowed',
 'Dogs Allowed',
 'Hardwood',
 'High Ceilings',
 'Light',
 'Pre-War',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Hardwood Floors',
 'Outdoor Space',
 'Roof Deck',
 'Dining Room',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Swimming Pool',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'doorman',
 'elevator',
 'Dogs Allowed',
 'Cats Allowed',
 'HIGHRISE',
 'LAUNDRY',
 'SIMPLEX',
 'HARDWOOD',
 'No Fee',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Loft',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Hardwood Floors',
 'No Fee',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Pre-War',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Hardwood Floors',
 'No Fee',
 'Balcony',
 'Pre-War',
 'Laundry in Unit',
 'Dishwasher',
 'Outdoor Space',
 'Dogs Allowed',
 'Cats Allowed',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Swimming Pool',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Garden/Patio',
 'Laundry in Building',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'New Construction',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'No Fee',
 'Doorman',
 'Elevator',
 'Pre-War',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'Elevator',
 'Laundry in Building',
 'Outdoor Space',
 'Doorman',
 'Fitness Center',
 'Elevator',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Terrace',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Doorman',
 'Elevator',
 'Terrace',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'Outdoor Space',
 'Pre-War',
 'Dishwasher',
 'Hardwood Floors',
 'Cats Allowed',
 'Dogs Allowed',
 'ACTUAL APT. PHOTOS',
 'Dishwasher',
 'Hardwood Floors',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'No Fee',
 'Reduced Fee',
 'Elevator',
 'Laundry In Building',
 'Subway',
 'High Speed Internet',
 'Hardwood',
 'High Ceilings',
 'Renovated',
 'Marble Bath',
 'Granite Kitchen',
 'Light',
 'Swimming Pool',
 'Dining Room',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Terrace',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry In Building',
 'Roof Deck',
 'Laundry in Building',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'New Construction',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Cats Allowed',
 'Dogs Allowed',
 'Elevator',
 'Laundry in Building',
 'Dishwasher',
 'No Fee',
 'Common Outdoor Space',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry In Building',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Dishwasher',
 'No Fee',
 'Elevator',
 'Cats Allowed',
 'Dogs Allowed',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Roof Deck',
 'Balcony',
 'Doorman',
 'Elevator',
 'Terrace',
 'Laundry in Building',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Pre-War',
 'Laundry in Building',
 'Hardwood Floors',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'No Fee',
 'Washer in Unit',
 'Dryer in Unit',
 'Dishwasher',
 'Cats Allowed',
 'Dogs Allowed',
 'Exclusive',
 'Doorman',
 'Elevator',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Elevator',
 'prewar',
 'Dogs Allowed',
 'Cats Allowed',
 'LOWRISE',
 'SIMPLEX',
 'HARDWOOD',
 'No Fee',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'No Fee',
 'Exclusive',
 'Doorman',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Dining Room',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Dining Room',
 'Balcony',
 'Elevator',
 'Loft',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'Outdoor Space',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Hardwood Floors',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Exclusive',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Fitness Center',
 'Pool',
 'Elevator',
 'Garage',
 'Cats Allowed',
 'Dogs Allowed',
 'Roof-deck',
 'Laundry Room',
 'Roof Deck',
 'Dining Room',
 'Elevator',
 'Pre-War',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'Dining Room',
 'Loft',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'New Construction',
 'Dogs Allowed',
 'Cats Allowed',
 'Elevator',
 'Newly renovated',
 'No pets',
 'Swimming Pool',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Roof Deck',
 'Balcony',
 'Doorman',
 'Elevator',
 'Garden/Patio',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'Outdoor Space',
 'Exclusive',
 'Elevator',
 'Cats Allowed',
 'Dogs Allowed',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'New Construction',
 'Dogs Allowed',
 'Cats Allowed',
 'Swimming Pool',
 'Roof Deck',
 'Dining Room',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Laundry in Unit',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'New Construction',
 'Dogs Allowed',
 'Cats Allowed',
 'Fitness Center',
 'Roof Deck',
 'WiFi Access',
 'Live-in Super',
 'Concierge',
 'Laundry in Building',
 'No Fee',
 'Exclusive',
 'Elevator',
 'Dining Room',
 'Balcony',
 'Elevator',
 'Loft',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Laundry in Unit',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Cats Allowed',
 'Dogs Allowed',
 'Dining Room',
 'Elevator',
 'Laundry in Building',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Doorman',
 'Fitness Center',
 'Dogs Allowed',
 'Cats Allowed',
 'Elevator',
 'Cats Allowed',
 'Dogs Allowed',
 'Exclusive',
 'Elevator',
 'Multi-Level',
 'Terrace',
 'Hardwood Floors',
 'Outdoor Space',
 'Doorman',
 'Dining Room',
 'Doorman',
 'Fitness Center',
 'Laundry in Building',
 'Laundry in Unit',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry In Building',
 'Fireplace',
 'Furnished',
 'Pre-War',
 'Laundry in Unit',
 'Hardwood Floors',
 'No Fee',
 'Dishwasher',
 'Hardwood Floors',
 'Hardwood Floors',
 'Outdoor Space',
 'Dogs Allowed',
 'Cats Allowed',
 'No Fee',
 'Dishwasher',
 'Hardwood Floors',
 'Furnished',
 'Laundry In Unit',
 'Cats Allowed',
 'Private Outdoor Space',
 'Dogs Allowed',
 'Parking Space',
 'Doorman',
 'Reduced Fee',
 'Elevator',
 'Short Term Allowed',
 'Fitness Center',
 'Exclusive',
 'Laundry In Building',
 'Sublet',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Pre-War',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Fitness Center',
 'Dogs Allowed',
 'Cats Allowed',
 'Roof Deck',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Hardwood Floors',
 'No Fee',
 'Pre-War',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Swimming Pool',
 'Dining Room',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Furnished',
 'Laundry in Building',
 'No Fee',
 'Doorman',
 'Prewar',
 'Fitness Center',
 'Elevator',
 'Garage',
 'Cats Allowed',
 'Dogs Allowed',
 'Roof-deck',
 'High Ceiling',
 'Laundry Room',
 'Balcony',
 'Elevator',
 'Loft',
 'Laundry in Building',
 'Hardwood Floors',
 'Outdoor Space',
 'Doorman',
 'Elevator',
 'Elevator',
 'Laundry in Building',
 'Elevator',
 'Loft',
 'Hardwood Floors',
 'Doorman',
 'Cats Allowed',
 'Dogs Allowed',
 'Fitness Center',
 'Pre-War',
 'No Fee',
 'Dogs Allowed',
 'Cats Allowed',
 'Dogs Allowed',
 'Cats Allowed',
 'Swimming Pool',
 'Roof Deck',
 'Dining Room',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Laundry in Unit',
 'High Speed Internet',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'New Construction',
 'Dogs Allowed',
 'Cats Allowed',
 'Doorman',
 'Elevator',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Laundry in Unit',
 'Dishwasher',
 'Hardwood Floors',
 'Exclusive',
 'Doorman',
 'Elevator',
 'Fitness Center',
 'Laundry in Building',
 'Dishwasher',
 'Hardwood Floors',
 'No Fee',
 'Outdoor Space',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'Actual Apt. Photos',
 'Loft',
 'Dishwasher',
 'Hardwood Floors',
 'Dogs Allowed',
 'Cats Allowed',
 'prewar',
 'Dogs Allowed',
 'Cats Allowed',
 'LOWRISE',
 'SIMPLEX',
 'HARDWOOD',
 'Doorman',
 'Elevator',
 ...]

### Сколько уникальных значений содержит список результатов?
### Давайте познакомимся с новой библиотекой — Collections. С помощью этого пакета вы сможете эффективно получать количественную статистику по вашим данным.

In [53]:
all_features_test = Counter(all_features_test)
all_features_test

Counter({'Elevator': 38229,
         'Cats Allowed': 35053,
         'Hardwood Floors': 34997,
         'Dogs Allowed': 32608,
         'Doorman': 30800,
         'Dishwasher': 30136,
         'No Fee': 26934,
         'Laundry in Building': 24193,
         'Fitness Center': 19764,
         'Pre-War': 13713,
         'Laundry in Unit': 12690,
         'Roof Deck': 9734,
         'Outdoor Space': 7923,
         'Dining Room': 7303,
         'High Speed Internet': 6189,
         'Balcony': 4510,
         'Swimming Pool': 4266,
         'Laundry In Building': 3874,
         'New Construction': 3717,
         'Terrace': 3201,
         'Exclusive': 3173,
         'Loft': 3098,
         'Garden/Patio': 2868,
         'Common Outdoor Space': 1984,
         'Wheelchair Access': 1945,
         'HARDWOOD': 1387,
         'SIMPLEX': 1373,
         'prewar': 1297,
         'Fireplace': 1240,
         'LOWRISE': 1201,
         'Laundry In Unit': 1153,
         'Reduced Fee': 1105,
         'Garage': 1104,
         'Laundry Room': 1042,
         'Furnished': 947,
         'Multi-Level': 892,
         'Private Outdoor Space': 807,
         'Prewar': 732,
         'Parking Space': 617,
         'PublicOutdoor': 592,
         'Roof-deck': 587,
         'dishwasher': 579,
         'High Ceilings': 512,
         'elevator': 480,
         'Renovated': 465,
         'Pool': 408,
         'LAUNDRY': 388,
         'HIGH CEILINGS': 375,
         'Green Building': 335,
         'LIVE IN SUPER': 326,
         'High Ceiling': 285,
         'Stainless Steel Appliances': 281,
         'Concierge': 249,
         'On-site laundry': 244,
         'Washer in Unit': 235,
         'Dryer in Unit': 235,
         'Live In Super': 230,
         'On-site Laundry': 226,
         'Storage': 224,
         'Newly renovated': 222,
         'On-site Garage': 203,
         'Hardwood': 200,
         'Light': 198,
         'Washer/Dryer': 184,
         'Gym/Fitness': 178,
         'Granite Kitchen': 168,
         'Walk in Closet(s)': 161,
         'Pets on approval': 160,
         'Patio': 150,
         'Live-in superintendent': 150,
         'Valet': 144,
         'Subway': 139,
         'Marble Bath': 138,
         'Residents Lounge': 137,
         'Full-time doorman': 126,
         'WiFi Access': 124,
         'Live-in Super': 120,
         'Common parking/Garage': 116,
         'EXPOSED BRICK': 115,
         'Parking': 111,
         'EAT IN KITCHEN': 109,
         'HIGHRISE': 108,
         'No pets': 108,
         'Short Term Allowed': 106,
         'Garden': 106,
         'Lounge': 106,
         'doorman': 104,
         'Childrens Playroom': 104,
         'Central A/C': 96,
         'Bike room': 96,
         'Luxury building': 93,
         'Common roof deck': 91,
         'Residents Garden': 87,
         'Outdoor Areas': 82,
         'ACTUAL APT. PHOTOS': 78,
         'Duplex': 77,
         'balcony': 75,
         'Indoor Pool': 71,
         'ROOFDECK': 65,
         'View': 64,
         'Virtual Doorman': 64,
         'building-common-outdoor-space': 62,
         'storage': 58,
         'Sublet': 57,
         'Washer & Dryer': 56,
         'Wheelchair Ramp': 55,
         'pool': 54,
         'Valet Parking': 53,
         "Children's Playroom": 53,
         'Sauna': 53,
         'Bike Room': 52,
         'patio': 51,
         'Air conditioning': 50,
         'Laundry': 49,
         'Gym': 49,
         'Health Club': 48,
         'Live/Work': 48,
         'Post-War': 48,
         'FT Doorman': 47,
         'Microwave': 46,
         'Lounge room': 45,
         'On-site Parking Lot': 44,
         'gym': 44,
         'Shares OK': 44,
         'private-outdoor-space': 43,
         'garden': 43,
         'Gym In Building': 43,
         'Courtyard': 43,
         'New construction': 42,
         'Washer/Dryer in building': 41,
         'Outdoor Entertainment Space': 41,
         'Live-In Superintendent': 40,
         'Exposed Brick': 40,
         'BROWNSTONE': 39,
         'MIDRISE': 39,
         'Hi Rise': 39,
         'Full Service Garage': 37,
         'Common terrace': 36,
         'Private outdoor space': 35,
         'Hardwood floors': 34,
         'private-balcony': 34,
         'Private balcony': 34,
         'Pet Friendly': 33,
         'Post War': 31,
         'Basement Storage': 30,
         'DECORATIVE FIREPLACE': 28,
         'Multi-level': 28,
         'In-Unit Washer/Dryer': 28,
         'Central AC': 28,
         'terrace': 27,
         'Eat In Kitchen': 26,
         'High-speed Internet': 26,
         'WALK IN CLOSET': 25,
         'Cable/Satellite TV': 25,
         'DINING ROOM': 24,
         'Rooftop Terrace': 24,
         'On-Site Parking': 24,
         'Flex-2': 24,
         'Skylight': 23,
         'Common garden': 23,
         'Common backyard': 22,
         'Business Center': 22,
         'on-site super': 22,
         'Marble Bathroom': 21,
         'Private backyard': 20,
         'Valet services including dry cleaning': 19,
         'Mail Room': 19,
         'Tenant Lounge': 19,
         'laundry & housekeeping': 18,
         'Private laundry room on every floor': 18,
         'view': 18,
         'Guarantors Accepted': 18,
         'Attended Lobby': 18,
         'storage room': 18,
         'Decorative Fireplace': 18,
         'BACKYARD': 18,
         'Flex-3': 17,
         'Concierge Service': 17,
         'central ac': 17,
         'garage': 17,
         'Laundry On Floor': 16,
         'fireplace': 16,
         'Sundeck': 16,
         'playroom/nursery': 16,
         'Shared backyard': 15,
         'DUPLEX': 15,
         'Deck': 15,
         'City view': 15,
         'All utilities included': 15,
         'Private Deck': 15,
         'Washer/Dryer in Unit': 14,
         'NO FEE': 14,
         'Video Intercom': 14,
         'Rooftop Deck': 14,
         'Community Recreation Facilities': 14,
         'Call/Text Abraham Caro @ 917-373-0862': 14,
         'Outdoor Pool': 14,
         'CONDO FINISHES': 14,
         'Actual Apt. Photos': 13,
         'GARDEN': 13,
         'Outdoor roof deck overlooking New York Harbor and Battery Park': 13,
         'BALCONY': 13,
         'WiFi': 13,
         'Eat-in Kitchen': 13,
         'High ceilings': 13,
         'Package Room': 13,
         'TONS OF NATURAL LIGHT': 13,
         'QUEEN SIZED ROOMS': 13,
         'CLOSETS GALORE!': 13,
         'CHEFS KITCHEN': 13,
         'Laundry in building': 12,
         'Game room': 12,
         'Private terrace': 12,
         'renovated': 12,
         'Screening Room': 12,
         'microwave': 12,
         'Basketball Court': 12,
         'Terraces / Balconies': 12,
         'All pets ok': 11,
         'Live in Super': 11,
         'Central Air': 11,
         'Roof access': 11,
         'Bike Storage': 11,
         'hardwood floors': 11,
         'Part-time doorman': 11,
         'S/S appliances': 11,
         'Complimentary Sunday brunch': 11,
         'Magnificent Venetian-Style': 10,
         'Fully  equipped': 10,
         'state-of-the-art fitness center': 10,
         'On-site Parking available': 10,
         'On-site ATM Machine': 10,
         'Storage Facilities available': 10,
         'Valet Services': 10,
         'Southern Exposure': 10,
         'Walk-In Closet': 10,
         '24/7 Doorman Concierge': 10,
         'Breakfast Bar': 10,
         'duplex': 10,
         'Virtual Tour': 10,
         'Party Room': 10,
         'Cable ready': 10,
         'Exposed brick': 10,
         'Granite Countertops': 10,
         'Close to subway': 10,
         'walk-up': 10,
         'Fireplaces': 10,
         'Shared garden': 9,
         'SS Appliances': 9,
         'Penthouse': 9,
         'Backyard': 9,
         'high ceilings': 9,
         'Gut Renovated': 9,
         '24/7 Concierge': 9,
         'Elegant glass-enclosed private lounge with magnificent river views': 9,
         'On-site parking available': 9,
         'pets allowed': 9,
         'pets': 8,
         'fitness center': 8,
         'Media Room': 8,
         'Billiards': 8,
         '24/7 Doorman': 8,
         'Live/work': 8,
         'On-site lifestyle concierge by Luxury Attaché': 8,
         'Billiards table and wet bar': 8,
         'Fully-equipped Club fitness center': 8,
         'Club sun deck has spectacular city and river views': 8,
         'Free WiFi in Club lounge': 8,
         'Garbage Disposal': 8,
         'Duplex Lounge': 8,
         'Valet Service': 8,
         'On-Site Attended Garage': 8,
         'Pre War': 8,
         'video intercom': 8,
         'newly renovated': 8,
         'Yoga Classes': 8,
         'DISHWASHER': 7,
         'HARDWOOD FLOORS': 7,
         'Washer/Dryer Hookup': 7,
         'Pets Allowed': 7,
         'Dry cleaning service': 7,
         'Housekeeping service': 7,
         'assigned-parking-space': 7,
         'Private parking': 7,
         'Deco Brick Wall': 7,
         'Yard': 7,
         'Parking Available': 7,
         'Wood-burning Fireplace': 7,
         'Queen Size Bedrooms': 7,
         'Roof deck': 7,
         'Playroom': 7,
         "Children's playroom": 7,
         'exposed brick': 7,
         'Billiards Room': 7,
         'Laundry on every floor': 7,
         'Skylight Atrium': 7,
         'Intercom': 7,
         'Brand New': 7,
         'Washer/Dryer in Bldg': 6,
         'Deco Brick Walls': 6,
         'Cinema Room': 6,
         'Skyline view': 6,
         'Renovated Kitchen': 6,
         'Video intercom': 6,
         'Venetian-style lobby': 6,
         '24 hour concierge/doorman': 6,
         'valet services (housekeeping/dry cleaning available)': 6,
         'on-site parking available': 6,
         'On-site ATM': 6,
         'Complimentary Sunday Brunch': 6,
         'Storage Facilities Available': 6,
         '24-hour doorman': 6,
         'French Doors': 6,
         'Private Balcony': 6,
         'Recessed Lighting': 6,
         'Fitness Room': 6,
         'Housekeeping + dry cleaning service': 6,
         'Roof decks': 6,
         'Live-in super': 5,
         'Wine Cooler': 5,
         'HEAT/HOT WATER INCLUDED': 5,
         'On-site parking': 5,
         'Walk-in Closet': 5,
         'deck': 5,
         'Private roofdeck': 5,
         'Roof': 5,
         'low-rise': 5,
         'Diplomats OK': 5,
         'laundry in building': 5,
         'One Month Free': 5,
         'Stone countertops': 5,
         'Pets: Cats/Small Dogs': 5,
         'On-site super': 5,
         'ELEVATOR': 5,
         'Central Heat': 5,
         'Private Terrace': 5,
         'mid-rise': 5,
         'Continental Breakfast': 5,
         'Twenty-four hour concierge and doorman': 5,
         'Skylights': 5,
         'Private garden': 5,
         'Valet services': 5,
         'Large Living Room': 5,
         '$250 Security Deposit': 5,
         'Close to Transit': 5,
         'King Sized Bedroom': 4,
         'Large Windows with Lots of Natural Sunlight': 4,
         'On-site Super': 4,
         'Outdoor terrace': 4,
         'Jacuzzi': 4,
         'Yoga Room': 4,
         'Super On-Site': 4,
         'stainless steel appliances': 4,
         'postwar': 4,
         'PENTHOUSE': 4,
         'Exposed Bricks': 4,
         'Bicycle Room': 4,
         'Open Kitchen': 4,
         'health club': 4,
         'On-Site Super': 4,
         'Basement': 4,
         '1 Month Free': 4,
         'Mint': 4,
         'laundry room': 4,
         'Extra room': 4,
         'On-site fitness center': 4,
         'featuring a two-story rock wall': 4,
         'Therapy room': 4,
         'Steam room and spa-style Room with large screen televisions': 4,
         'Rooftop deck to soak in stunning city views': 4,
         'Storage Available': 4,
         'Restaurant': 4,
         'OUTDOOR SPACE': 4,
         'backyard': 4,
         'parking': 4,
         'Queen Size Bedroom': 4,
         'Crown Moldings': 4,
         'bright': 4,
         'Close to subway and park': 4,
         'Parking Garage': 4,
         'High Speed Internet Available': 4,
         'Complimentary Continental Breakfast': 4,
         'Valet Laundry': 4,
         'Dry Cleaning Service': 4,
         'Electronic Rent Payment': 4,
         'Outdoor Basketball Court': 4,
         'Wifi in Resident Lounge': 4,
         'RENOVATED': 3,
         'Dish Washer': 3,
         'Multi Level': 3,
         'Seperate Kitchen': 3,
         'Deco French Doors': 3,
         'Granite Counters': 3,
         '24-hour Attended Lobby': 3,
         'Landscaped Roofdeck': 3,
         'Community Lounge': 3,
         'Wi Fi Work Lounge': 3,
         'Full Time Porter': 3,
         'Granite countertops': 3,
         'GUT RENOVATED': 3,
         'Queen Sized Bedrooms': 3,
         'Fitness Facility': 3,
         'Large Living-room': 3,
         'penthouse': 3,
         'marble bathroom': 3,
         'pets ok': 3,
         'Large Bedroom': 3,
         'Rooftop': 3,
         'Bicycle Storage': 3,
         '3': 3,
         'F': 3,
         'Poker Table': 3,
         'Yoga Studio': 3,
         'Underground parking': 3,
         'Storage in basement': 3,
         'Close to hospitals': 3,
         'Private Storage': 3,
         '1 MONTH FREE': 3,
         'Granite Counter': 3,
         'separate kitchen': 3,
         'New Kitchen': 3,
         'Storage Loft': 3,
         'Pet friendly': 3,
         'Triplex': 3,
         'Bike storage': 3,
         '24 Hour Doorman': 3,
         'State-of-the-Art Cardio and Fitness Club': 3,
         'On-site Resident Manager': 3,
         'Expansive Sundeck': 3,
         'Tenant Storage': 3,
         'Hardwood Floor': 3,
         'Low Fee': 3,
         'live in super': 3,
         'rooftop deck': 3,
         'Corner Unit': 3,
         'Private Roof Deck': 3,
         'Bright': 3,
         'Indoor swimming pool': 3,
         'Sun Deck: soak up the sun or just sit and enjoy the views': 3,
         'Gym: State-of-the-art Techno Gym cardio and weight training equipment': 3,
         'Lounge: Relax': 3,
         'Read': 3,
         'Play Billiards or entertain in the lounge': 3,
         'roof deck': 3,
         'new kitchen': 3,
         'tenants lounge with free Wi-Fi': 3,
         'Queen Sized Bedroom': 3,
         'Large Living room': 3,
         'Central Air Conditioning': 3,
         'State': 3,
         'art fitness center': 3,
         'Laundry and housekeeping available': 3,
         'Media Screening Room': 3,
         'Roof Deck with Grills': 3,
         'Children’s Playroom.': 3,
         'Cold Storage': 3,
         'Common balcony': 3,
         '4 Separate Roof Decks': 3,
         'bike storage': 3,
         'DW': 3,
         'Common Storage': 3,
         'Alcove': 3,
         'Separate Kitchen': 3,
         'Dining/living room': 3,
         'share ok': 3,
         'closet space': 3,
         'Balconies in both bedrooms': 3,
         'low-rise.': 3,
         'Granite Counter-Tops': 3,
         'Twenty-four-hour concierge and doorman': 3,
         'Jacuzzi bath tube': 3,
         'Dining Area': 3,
         '24 hour doorman': 3,
         'Roofdeck': 3,
         'lounge': 3,
         'bike room': 3,
         'MW & DW': 3,
         'stainless steel': 3,
         'Private Backyard': 3,
         'Home Office': 3,
         "children's playroom": 3,
         'Pets - case by case.': 3,
         'laundry': 3,
         'W/D': 3,
         'Fully Renovated': 3,
         'Loft Style': 3,
         'LIGHT': 3,
         'Wi-Fi Access': 3,
         'Heat': 3,
         'Hardwood Flooring': 3,
         'Stainless Steel appliances': 2,
         'Great Location!': 2,
         'Dark Hardwood Floors': 2,
         'Park view': 2,
         'water view': 2,
         'Sun-drenched': 2,
         'Built in microwave': 2,
         'Private roof Deck': 2,
         'hardwood': 2,
         '1.5 Bath': 2,
         'Spacious': 2,
         'Actual Photos!': 2,
         'Steam Room': 2,
         'Laundry on Each Floor': 2,
         'Cabanas': 2,
         'Kinesis Room': 2,
         'Indoor Basketball Court': 2,
         'Landscaped Terrace with BBQ Grill': 2,
         'Refrigerated Storage for Perishable Deliveries': 2,
         'Pet-Friendly': 2,
         'Close to 1': 2,
         '2': 2,
         'B': 2,
         'D': 2,
         'M': 2,
         'N': 2,
         'Q': 2,
         'and R Subway Stations': 2,
         'Fine Bars and Restaurants': 2,
         'Extra Room': 2,
         'valet services': 2,
         'Heat & Hot Water Included': 2,
         'Storage Space': 2,
         'Storage available': 2,
         '24hr doorman': 2,
         'Luxury Building': 2,
         'Laundry in unit': 2,
         'massive 1 bed': 2,
         'sun drenched': 2,
         'Great Closet Space': 2,
         'Shared Roof Deck': 2,
         'Brand Spanking New': 2,
         'Stainless Steel': 2,
         'Great Natural Light': 2,
         'heat and hot water included in rental price': 2,
         'Open View': 2,
         'Double Exposure': 2,
         'Mullion Pane Windows': 2,
         'natural light': 2,
         'Bluetooth': 2,
         'New Bathroom': 2,
         '24 hour attended lobby': 2,
         'Double height lobby French limestone and Rojo Alicante marble': 2,
         'Comprehensive valet services including maid service': 2,
         'laundry / dry-cleaning and auto care': 2,
         'Building Link Notification & Key Track for tenants convenience': 2,
         'Closed circuit television security system': 2,
         'Bicycle and tenant st...orage available for rent': 2,
         'specific dog breeds up to 40lbs': 2,
         'Live-In Resident Manager': 2,
         '& ATM machine on-site': 2,
         'Spacious Living Room': 2,
         'Pets: Cats Only': 2,
         'Working Fireplace': 2,
         'DishwasherHardwood Floors MicrowaveRenovated': 2,
         'Modern Finishes': 2,
         'Washer/Dryer In Unit': 2,
         'Common courtyard': 2,
         'Balcony/Terrace': 2,
         'Roof Access': 2,
         'PRIVATE TERRACE': 2,
         'Extra Storage': 2,
         'high ceiling': 2,
         'townhouse': 2,
         'Oversized Windows': 2,
         'Free Laundry': 2,
         'Pets: Case by case': 2,
         'billiards room': 2,
         'Pets Case by Case': 2,
         'Brownstone': 2,
         'floor to ceiling windows': 2,
         'sauna': 2,
         'Walk Up': 2,
         'Pre-war': 2,
         'spacious': 2,
         '2 Full Bathrooms': 2,
         'Free Wifi': 2,
         'Townhouse': 2,
         'One Month Free Rent!': 2,
         'designer lobby & common areas': 2,
         'furnished roof deck': 2,
         'and valet services': 2,
         'LARGE BEDROOMS': 2,
         'TRIPLEX': 2,
         'Unassigned Paid parking available nearby': 2,
         'A Full service Luxury Highrise': 2,
         'Immaculate': 2,
         'Video Security': 2,
         'One Month Fee': 2,
         'Close to Subway': 2,
         'East Exposure': 2,
         'Spiral Staircase': 2,
         'Security System': 2,
         '9-Foot Ceilings': 2,
         'Eastern Exposure': 2,
         'Floor-to-Ceiling Windows': 2,
         'Sunny': 2,
         'CONVERTIBLE 3 BEDROOM': 2,
         'real 2 bedroom': 2,
         'new bathroom': 2,
         'West Village': 2,
         'Meat Packing': 2,
         'Tree Lined Block': 2,
         'Stainless steel appliances': 2,
         'washer/dryer': 2,
         'lots of sunlight': 2,
         'Lounge/ Game Room': 2,
         'Over-Sized Windows': 2,
         'Eat-in kitchen': 2,
         'Movie Theater': 2,
         'two month free rent': 2,
         'Stainless Appliances': 2,
         'Exercise/Yoga Studio': 2,
         'Spa Services': 2,
         'Washer/Dryer In-Unit': 2,
         'Postwar': 2,
         'roof access': 2,
         'Diplomats welcome': 2,
         'Custom Renovations': 2,
         'Light Filled': 2,
         'Queen size bedrooms': 2,
         '4': 2,
         'Large backyard': 2,
         'eat-in kitchen': 2,
         'ONE MONTH FEE': 2,
         'high floor': 2,
         'washer dryer hook up': 2,

In [54]:
len(all_features_test)

2068

In [55]:
all_features_train = Counter(all_features_train)
all_features_train

Counter({'Elevator': 25375,
         'Hardwood Floors': 23146,
         'Cats Allowed': 23135,
         'Dogs Allowed': 21652,
         'Doorman': 20479,
         'Dishwasher': 20081,
         'No Fee': 17793,
         'Laundry in Building': 16082,
         'Fitness Center': 12989,
         'Pre-War': 8971,
         'Laundry in Unit': 8437,
         'Roof Deck': 6417,
         'Outdoor Space': 5132,
         'Dining Room': 4890,
         'High Speed Internet': 4223,
         'Balcony': 2898,
         'Swimming Pool': 2643,
         'Laundry In Building': 2564,
         'New Construction': 2504,
         'Terrace': 2177,
         'Exclusive': 2075,
         'Loft': 2039,
         'Garden/Patio': 1878,
         'Wheelchair Access': 1311,
         'Common Outdoor Space': 1280,
         'HARDWOOD': 880,
         'SIMPLEX': 873,
         'Fireplace': 837,
         'prewar': 820,
         'LOWRISE': 764,
         'Garage': 736,
         'Laundry Room': 712,
         'Reduced Fee': 686,
         'Laundry In Unit': 685,
         'Furnished': 668,
         'Multi-Level': 592,
         'Private Outdoor Space': 501,
         'Prewar': 487,
         'PublicOutdoor': 419,
         'Parking Space': 412,
         'Roof-deck': 388,
         'dishwasher': 377,
         'High Ceilings': 359,
         'elevator': 343,
         'Renovated': 319,
         'Pool': 275,
         'LAUNDRY': 255,
         'Green Building': 233,
         'HIGH CEILINGS': 230,
         'LIVE IN SUPER': 206,
         'High Ceiling': 196,
         'Washer in Unit': 183,
         'Dryer in Unit': 183,
         'Storage': 168,
         'On-site laundry': 167,
         'Stainless Steel Appliances': 167,
         'Concierge': 164,
         'Newly renovated': 153,
         'On-site Laundry': 147,
         'Hardwood': 144,
         'Light': 144,
         'Live In Super': 142,
         'On-site Garage': 140,
         'Washer/Dryer': 128,
         'Granite Kitchen': 116,
         'Gym/Fitness': 114,
         'Pets on approval': 107,
         'Marble Bath': 106,
         'Walk in Closet(s)': 102,
         'Subway': 100,
         'Patio': 98,
         'Residents Lounge': 98,
         'Valet': 93,
         'Live-in superintendent': 90,
         'Common parking/Garage': 89,
         'Full-time doorman': 83,
         'WiFi Access': 81,
         'Live-in Super': 81,
         'EAT IN KITCHEN': 81,
         'Parking': 81,
         'EXPOSED BRICK': 74,
         'Childrens Playroom': 74,
         'Short Term Allowed': 74,
         'Lounge': 73,
         'HIGHRISE': 73,
         'doorman': 69,
         'Garden': 68,
         'No pets': 67,
         'Bike room': 66,
         'Central A/C': 61,
         'Duplex': 60,
         'Luxury building': 56,
         'balcony': 55,
         'ACTUAL APT. PHOTOS': 55,
         'Residents Garden': 55,
         'Common roof deck': 53,
         'Outdoor Areas': 52,
         'ROOFDECK': 49,
         'Indoor Pool': 48,
         'storage': 47,
         'New construction': 47,
         'View': 45,
         'Lounge room': 44,
         'Bike Room': 42,
         'Virtual Doorman': 42,
         'pool': 40,
         'patio': 38,
         'building-common-outdoor-space': 37,
         'Air conditioning': 36,
         'Valet Parking': 36,
         "Children's Playroom": 34,
         'Courtyard': 34,
         'Washer & Dryer': 33,
         'Shares OK': 33,
         'Sauna': 32,
         'Wheelchair Ramp': 31,
         'Gym': 31,
         'private-balcony': 30,
         'Private balcony': 30,
         'Live/Work': 30,
         'terrace': 30,
         'Health Club': 29,
         'Microwave': 28,
         'FT Doorman': 28,
         'Full Service Garage': 28,
         'Washer/Dryer in building': 28,
         'Outdoor Entertainment Space': 28,
         'Live-In Superintendent': 28,
         'Laundry': 27,
         'gym': 27,
         'Exposed Brick': 26,
         'Post-War': 25,
         'On-site Parking Lot': 25,
         'Basement Storage': 25,
         'Private outdoor space': 24,
         'garden': 23,
         'BROWNSTONE': 23,
         'Hi Rise': 23,
         'In-Unit Washer/Dryer': 23,
         'private-outdoor-space': 21,
         'Common terrace': 21,
         'Post War': 21,
         'on-site super': 21,
         'Concierge Service': 20,
         'MIDRISE': 20,
         'Hardwood floors': 19,
         'Pet Friendly': 18,
         'DECORATIVE FIREPLACE': 17,
         'Sublet': 17,
         'On-Site Parking': 17,
         'WALK IN CLOSET': 17,
         'Guarantors Accepted': 16,
         'Private backyard': 16,
         'Attended Lobby': 16,
         'Rooftop Terrace': 16,
         'Private terrace': 16,
         'Business Center': 16,
         'storage room': 16,
         'NO FEE': 15,
         'Common garden': 15,
         'assigned-parking-space': 15,
         'Private parking': 15,
         'Deck': 15,
         'High-speed Internet': 15,
         'Terraces / Balconies': 14,
         'Common backyard': 14,
         'playroom/nursery': 14,
         'Package Room': 13,
         'Flex-2': 13,
         'Cable/Satellite TV': 12,
         'Eat In Kitchen': 12,
         'Actual Apt. Photos': 12,
         'Community Recreation Facilities': 12,
         'Outdoor Pool': 12,
         'view': 12,
         'Skylight': 11,
         'DINING ROOM': 11,
         'Laundry On Floor': 11,
         'Shared backyard': 11,
         'garage': 11,
         'Mail Room': 11,
         'BALCONY': 10,
         'Live/work': 10,
         'Washer/Dryer in Unit': 10,
         'Gym In Building': 9,
         'Central Air': 9,
         'renovated': 9,
         'Marble Bathroom': 9,
         'Fireplaces': 9,
         'Bike Storage': 9,
         'Eat-in Kitchen': 9,
         'Decorative Fireplace': 9,
         'Multi-level': 9,
         'Private Deck': 9,
         'Tenant Lounge': 9,
         'Central AC': 9,
         'High ceilings': 8,
         'Roof deck': 8,
         'Media Room': 8,
         '24/7 Concierge': 8,
         'Rooftop Deck': 8,
         'Screening Room': 8,
         'Valet services including dry cleaning': 8,
         'laundry & housekeeping': 8,
         'Private laundry room on every floor': 8,
         'BACKYARD': 8,
         'valet': 8,
         'Valet Services': 8,
         'high ceilings': 8,
         'Sundeck': 8,
         'Playroom': 7,
         'Video Intercom': 7,
         'hardwood floors': 7,
         'WiFi': 7,
         '24/7 Doorman': 7,
         'Washer/Dryer Hookup': 7,
         'Parking Available': 7,
         'Gut Renovated': 7,
         'pets': 7,
         'fireplace': 7,
         'DUPLEX': 7,
         'All utilities included': 7,
         'exposed brick': 7,
         'Jacuzzi': 7,
         'central ac': 7,
         'Garbage Disposal': 7,
         'City view': 7,
         'pets allowed': 7,
         'TONS OF NATURAL LIGHT': 7,
         'QUEEN SIZED ROOMS': 7,
         'CLOSETS GALORE!': 7,
         'CHEFS KITCHEN': 7,
         'CONDO FINISHES': 7,
         'Roof access': 6,
         'Laundry in building': 6,
         'Backyard': 6,
         'Walk-In Closet': 6,
         'On-site super': 6,
         'Pets Allowed': 6,
         'Flex-3': 6,
         'Storage Available': 6,
         'Wood-burning Fireplace': 6,
         'Housekeeping service': 5,
         'Private Terrace': 5,
         'Breakfast Bar': 5,
         'New Renovation': 5,
         'lounge': 5,
         'roof deck': 5,
         'Party Room': 5,
         'Magnificent Venetian-Style': 5,
         'Fully  equipped': 5,
         'state-of-the-art fitness center': 5,
         'On-site Parking available': 5,
         'On-site ATM Machine': 5,
         'Outdoor roof deck overlooking New York Harbor and Battery Park': 5,
         'Storage Facilities available': 5,
         'RENOVATED': 5,
         'Private garden': 5,
         'Exposed brick': 5,
         'deck': 5,
         'Private roofdeck': 5,
         'Large Living Room': 5,
         'Actual Photos!': 5,
         'Cinema Room': 5,
         'Park view': 5,
         'Virtual Tour': 5,
         'Penthouse': 5,
         'Fitness Room': 5,
         'S/S appliances': 5,
         'Billiards Room': 5,
         'parking': 5,
         'Crown Moldings': 5,
         'video intercom': 5,
         'Part-time doorman': 5,
         'Home Office': 4,
         'Newly Renovated': 4,
         'Screening room': 4,
         'On-site parking': 4,
         'Pets: Cats/Small Dogs': 4,
         'business center': 4,
         'HARDWOOD FLOORS': 4,
         'GARDEN': 4,
         'sauna': 4,
         'Bright': 4,
         'Close to subway': 4,
         'Spacious': 4,
         'Granite Counter Tops': 4,
         'laundry room': 4,
         'Yard': 4,
         'Valet Service': 4,
         'microwave': 4,
         'Renovated Kitchen': 4,
         'Cable ready': 4,
         'rooftop deck': 4,
         'common storage': 4,
         'One Month Free': 4,
         'walk-up': 4,
         'Call/Text Abraham Caro @ 917-373-0862': 4,
         'Private Roof Deck': 4,
         'Yoga Classes': 4,
         'Live in Super': 4,
         'Live-In Super': 4,
         'Granite countertops': 3,
         'fitness center': 3,
         'Shared garden': 3,
         'Package service': 3,
         'Free Wifi': 3,
         'Stainless Steel': 3,
         'Granite Counters': 3,
         'Diplomats OK': 3,
         'Package & grocery delivery storage': 3,
         'Full size gym': 3,
         'Yoga / dance studio': 3,
         'Movie theater': 3,
         'Children playroom': 3,
         'Gardening area with rentable plots': 3,
         'Bike & stroller storage': 3,
         'Pet grooming room': 3,
         'Stunning roof deck with breathtaking views': 3,
         'Roof grilling area': 3,
         'Rentable': 3,
         'fully equipped chef’s kitchen with private roof deck': 3,
         'Party room': 3,
         'Deco Brick Wall': 3,
         'walk in closet': 3,
         'French Doors': 3,
         'Large Living-room': 3,
         'Bright & Sunny': 3,
         'Gas Included': 3,
         'Low Fee': 3,
         'Large Windows with Lots of Natural Light': 3,
         "children's playroom": 3,
         'Skylights': 3,
         'Queen Sized Bedrooms': 3,
         'All pets ok': 3,
         'Bike storage': 3,
         'Game room': 3,
         'On-site Super': 3,
         'Oak Floors': 3,
         'Storage Space': 3,
         'On-site lifestyle concierge by Luxury Attaché': 3,
         'Elegant glass-enclosed private lounge with magnificent river views': 3,
         'Billiards table and wet bar': 3,
         'Fully-equipped Club fitness center': 3,
         'Club sun deck has spectacular city and river views': 3,
         'Complimentary Sunday brunch': 3,
         'On-site parking available': 3,
         'Free WiFi in Club lounge': 3,
         'Recessed Lighting': 3,
         'Utilities Included': 3,
         'Bluetooth': 3,
         '24 hr doorman': 3,
         'Original Details': 3,
         'Dry cleaning service': 3,
         'Unassigned Paid parking available nearby': 3,
         'Dining room': 3,
         '24/7 Doorman Concierge': 3,
         'Spa Services': 3,
         'Cold Storage': 3,
         'bike room': 3,
         'billiards room': 3,
         'water filtration system': 3,
         'fitness facility': 3,
         'exercise studio': 3,
         'steam room': 3,
         'private storage': 3,
         'DW': 3,
         'Brand New': 3,
         'Window Bath': 3,
         'Private roof access': 3,
         'Skylight Atrium': 3,
         'Duplex Lounge': 3,
         'On-Site Attended Garage': 3,
         'Close to Subway': 3,
         'townhouse': 3,
         'Roofdeck': 3,
         'Laundry on every floor': 3,
         'Live Work': 3,
         'High Speed Internet Available': 3,
         'Valet Laundry': 3,
         'Dry Cleaning Service': 3,
         'Outdoor Basketball Court': 3,
         'Yoga Room': 3,
         'deco fireplace': 3,
         'Children’s Playroom': 3,
         '24-hour doorman': 3,
         'Wi-Fi Access': 3,
         'Washer/Dryer in Bldg': 3,
         'stainless steel appliances': 3,
         'Multi Level': 3,
         'Underground Parking': 3,
         'Roof Deck with real grass': 3,
         'Rent Stabalized': 3,
         'Billiards Lounge': 3,
         'Outdoor BBQs': 3,
         'Leed Certified': 3,
         '24HR Doorman': 3,
         'Convinient to all major transportation': 3,
         'Outstanding Shopping': 3,
         'separate kitchen': 3,
         'Pre War': 3,
         'Built in microwave': 2,
         'Finished Basement': 2,
         'King Sized Bedroom': 2,
         "children's room": 2,
         '24hr doorman': 2,
         'Natural Light': 2,
         'River view': 2,
         'Stainless steel appliances': 2,
         'King Size Bedrooms': 2,
         'Unassigned Paid parking available': 2,
         'Sunny': 2,
         'Hardwood Floor': 2,
         'Live-in super': 2,
         'private backyard': 2,
         'in unit washer and dryer': 2,
         'Union Square': 2,
         'HEAT/HOT WATER INCLUDED': 2,
         'Extra room': 2,
         'Heat Included': 2,
         'Eat-in kitchen': 2,
         'Laundry room on every floor. Health club': 2,
         'indoor swimming pool': 2,
         'sundeck with BBQ grills': 2,
         'misting shower and resident lounge available.': 2,
         'floor to ceiling windows': 2,
         'Mint': 2,
         'A Full Service luxury Highrise': 2,
         'Exposed Brick Wall': 2,
         'Pets allowed': 2,
         'Poker Table': 2,
         "Children's playroom": 2,
         'stainless steel': 2,
         'Working Fireplace': 2,
         'Super On-Site': 2,
         'Free Gym': 2,
         'Grand Central': 2,
         'closet space': 2,
         'Southern exposure': 2,
         'Sunny Southern Exposure': 2,
         'Storage space': 2,
         'Skyline view': 2,
         'Granite Countertops': 2,
         'Stainless Appliances': 2,
         'DISHWASHER': 2,
         'Flex-1': 2,
         'Great Closet Space': 2,
         'One small dog ok on approval': 2,
         'Twenty-four hour concierge and doorman': 2,
         'Extra Room': 2,
         'Southern Exposure': 2,
         'Queen Sized Bedroom': 2,
         'Extra Closet Space': 2,
         'Dish Washer': 2,
         'Deco Fireplace': 2,
         'valet parking': 2,
         'Extra Storage': 2,
         'Garage.': 2,
         'In unit washer and dryer': 2,
         'lounge area': 2,
         'Fitness center': 2,
         'Renovated Bathroom': 2,
         'Closets': 2,
         '2 Full Baths': 2,
         'A Full service Luxury Highrise': 2,
         '<null>': 2,
         'BUILT-IN SPEAKER SYSTEM': 2,
         'Large windows': 2,
         'kitchen island': 2,
         'Breakfast bar': 2,
         'Media Screening Room': 2,
         'Exercise/Yoga Studio': 2,
         'Roof Deck with Grills': 2,
         'Washer/Dryer In-Unit': 2,
         'Recessed Lighting.': 2,
         'Central Heat': 2,
         'Stainless Steel Kitchen': 2,
         'Huge': 2,
         'one month free rent': 2,
         'Rent Stabilized': 2,
         'Gramercy Park': 2,
         'Full service Luxury Highrise': 2,
         '24 Hour Doorman': 2,
         'State-of-the-Art Cardio and Fitness Club': 2,
         'On-site Resident Manager': 2,
         'Expansive Sundeck': 2,
         'Tenant Storage': 2,
         'Open Layout': 2,
         'Water Views': 2,
         'No Fee!': 2,
         'Pre-war Charm': 2,
         'Foyer': 2,
         'SSA Kitchen': 2,
         'Intercom': 2,
         'rooftop': 2,
         'MW': 2,
         'Window Kitchen': 2,
         'King Size Bedroom': 2,
         'On-Site Super': 2,
         'Balconies in both bedrooms': 2,
         '24/7 Full-Time Doorman Concierge': 2,
         'Short term': 2,
         'newly renovated': 2,
         'heat hot water included': 2,
         'huge room': 2,
         'Complimentary Continental Breakfast': 2,
         'Electronic Rent Payment': 2,
         'Wifi in Resident Lounge': 2,
         'Stainless Steel appliances': 2,
         'NO PETS': 2,
         'Eat in Kitchen': 2,
         'Business center': 2,
         'Marble bath': 2,
         'SS appliances': 2,
         "Chef's kitchen": 2,
         'elevator & Laundry': 2,
         'PRIVATE BALCONY': 2,
         'share ok': 2,
         'King Bedrooms': 2,
         'housekeeping': 2,
         'Pets - case by case.': 2,
         'SPACE': 2,
         'LIGHT': 2,
         'Stainless Steal Appliances': 2,
         '1 Month Free': 2,
         'Hardwood Flooring': 2,
         'Full-service condominium': 2,
         'Garage attached': 2,
         'Storage room': 2,
         'Lounge spaces': 2,
         'Health club with pool on the top floor': 2,
         'Yoga and Spin Studios': 2,
         'Large Windows w/ lots of Natural Light': 2,
         'On site super': 2,
         'Corner Unit': 2,
         'Close to Transit': 2,
         'Common Storage': 2,
         'Granite Counter': 2,
         'ALL UTILITIES INCLUDED': 2,
         'Triplex': 2,
         'Manhattan Views': 2,
         'Available 05/01/16': 2,
         'Laundry in Some Units': 2,
         'Utilities included': 1,
         'Private Entrances': 1,
         'Top Floor Unit': 1,
         'XXL Windows': 1,
         'pet friendly': 1,
         'water view': 1,
         '24hr doormen': 1,
         'package service': 1,
         'dry cleaning service': 1,
         'Sleep Loft': 1,
         'own entrance': 1,
         'oak cabinets': 1,
         '** HOLY NO FEE DEAL BATMAN! * OVERSIZED 2BR HOME * SPARKLING CLEAN & BRITE * HEART OF GREENPOINT * NEAR THE PARK & TRAINS **': 1,
         'Recreational Room': 1,
         'Townhouse': 1,
         'dry-cleaning service': 1,
         'Washer': 1,
         '!!!!LOW FEE!!!!': 1,
         '** CHELSEA BABY! * MASSIVE 2BR SUPER SHARE * ALL MODERN & NEW * ELEV /LNDRY BLDG **': 1,
         'Loft Area': 1,
         'Flex two bed': 1,
         'Superintendent lives in': 1,
         '** SPRAWLING STUDIO HOME * DISHWASHER * EXPOSED BRICK * GUT RENOVATED * PETS OK * STEPS TO THE PARK **': 1,
         'Control & pay for your own heat with your own thermostat': 1,
         'NO alternate side parking rules in neighborhood': 1,
         'Previous tenant found easy on-street parking.': 1,
         'Citi Bike Station': 1,
         'Garage Parking!': 1,
         '** COURT SQUARE GEM! * SPRAWLING SUNDRENCHED 2BR HOME * CUSTOM FINISHES * DISHWASHER * FIREPLACES * EAT-IN KITCHEN * BAY WINDOWS **': 1,
         'Recently renovated': 1,
         '2 blocks away from Union Square': 1,
         'Combo Washer Dryer': 1,
         'Bridge View': 1,
         'Shared yard': 1,
         'Outdoor play area': 1,
         'Washer and dryer in unit': 1,
         'Walk-in closet': 1,
         "Children's room": 1,
         'build-in Microwave-oven': 1,
         'ceiling-fan...': 1,
         '** UNIQUE FIND! * SPRAWLING 2BR SUPER SHARE * WALLS OF WINDOWS * STUNNING RENOVATIONS * 2 BLKS TO BEDFORD L STOP **': 1,
         'Expansive Living-room': 1,
         '** OVERSIZED 1BR HOME * GUT RENOVATED * PERFECT NATURAL LIGHT * HEART OF CHELSEA * PETS OK **': 1,
         'A full service Luxury highrise': 1,
         'Queen & King Size Bedrooms': 1,
         'Large Living room': 1,
         '4th off Charles': 1,
         'ALL NEW': 1,
         'Loft Like': 1,
         'Big Rooms': 1,
         'The Most Sought after Location': 1,
         'Lots of Light': 1,
         'pets upon approval': 1,
         'Resident Super in the building': 1,
         '** OVERSIZED 2BR SUPER SHARE * FRENCH DOORS * SS EAT-IN KITCHEN * MR CLEAN APPROVED * HEART OF MIDTOWN! **': 1,
         'Diswasher': 1,
         'ELEVATOR/LAUNDRY/ SO CLOSE TO THE 6 $2450!!': 1,
         'Hot Water Inc. HUGE Walk-In Closet or Extra Room!': 1,
         'Air Conditioning': 1,
         'Near Subway': 1,
         'Near PRATT': 1,

In [56]:
len(all_features_train)

1539

### Подсчитайте самые популярные функции из нашего огромного списка и выберите 20 лучших на данный момент.

In [58]:
top20_features_train = sorted(all_features_train.items(), key=lambda x: x[1], reverse=True)[:20]
top20_features_train

[('Elevator', 25375),
 ('Hardwood Floors', 23146),
 ('Cats Allowed', 23135),
 ('Dogs Allowed', 21652),
 ('Doorman', 20479),
 ('Dishwasher', 20081),
 ('No Fee', 17793),
 ('Laundry in Building', 16082),
 ('Fitness Center', 12989),
 ('Pre-War', 8971),
 ('Laundry in Unit', 8437),
 ('Roof Deck', 6417),
 ('Outdoor Space', 5132),
 ('Dining Room', 4890),
 ('High Speed Internet', 4223),
 ('Balcony', 2898),
 ('Swimming Pool', 2643),
 ('Laundry In Building', 2564),
 ('New Construction', 2504),
 ('Terrace', 2177)]

### Теперь создайте 20 новых признаков на основе 20 верхних значений: 1, если значение находится в столбце «Признак», в противном случае 0.

In [60]:
for feature, _ in top20_features_train:
    train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
    test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))

/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[feature] = train_df["features"].apply(lambda x: int(feature in x))
/tmp/ipykernel_34276/531982656.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[feature] = test_df["features"].apply(lambda x: int(feature in x))

In [67]:
test_df.head()

,bathrooms,bedrooms,features,price,Elevator,Hardwood Floors,Cats Allowed,Dogs Allowed,Doorman,Dishwasher,...,Laundry in Unit,Roof Deck,Outdoor Space,Dining Room,High Speed Internet,Balcony,Swimming Pool,Laundry In Building,New Construction,Terrace
0,1.0,1,"[Elevator, Laundry in Building, Laundry in Uni...",2950,1,1,0,0,0,1,...,1,0,1,0,0,0,0,0,0,0
1,1.0,2,"[Pre-War, Dogs Allowed, Cats Allowed]",2850,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.0,0,"[Pre-War, Dogs Allowed, Cats Allowed]",2295,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1.0,2,"[Hardwood Floors, Dogs Allowed, Cats Allowed]",2900,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1.0,1,"[Roof Deck, Doorman, Elevator, Fitness Center,...",3254,1,0,1,1,1,0,...,0,1,0,0,1,0,0,0,0,0

In [69]:
train_df.head()

,bathrooms,bedrooms,features,price,Elevator,Hardwood Floors,Cats Allowed,Dogs Allowed,Doorman,Dishwasher,...,Laundry in Unit,Roof Deck,Outdoor Space,Dining Room,High Speed Internet,Balcony,Swimming Pool,Laundry In Building,New Construction,Terrace
4,1.0,1,"[Dining Room, Pre-War, Laundry in Building, Di...",2400,0,1,1,1,0,1,...,0,0,0,1,0,0,0,0,0,0
6,1.0,2,"[Doorman, Elevator, Laundry in Building, Dishw...",3800,1,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
9,1.0,2,"[Doorman, Elevator, Laundry in Building, Laund...",3495,1,1,0,0,1,1,...,1,0,0,0,0,0,0,0,0,0
10,1.5,3,[],3000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1.0,0,"[Doorman, Elevator, Fitness Center, Laundry in...",2795,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

### Расширьте наш набор признаков, добавив «ванные комнаты» и «спальни», и создайте специальную переменную feature_list с названиями всех признаков. Теперь у нас 22 значения. Все модели должны быть обучены на этих 22 признаках.

In [72]:
train_df = train_df.drop("features",axis=1)
test_df = test_df.drop("features",axis=1)

X_train = train_df.drop('price', axis=1) 
y_train = train_df['price']  

X_test = test_df.drop('price', axis=1) 
y_test = test_df['price'] 

feature_list = X_train.columns

In [74]:
feature_list

Index(['bathrooms', 'bedrooms', 'Elevator', 'Hardwood Floors', 'Cats Allowed',
       'Dogs Allowed', 'Doorman', 'Dishwasher', 'No Fee',
       'Laundry in Building', 'Fitness Center', 'Pre-War', 'Laundry in Unit',
       'Roof Deck', 'Outdoor Space', 'Dining Room', 'High Speed Internet',
       'Balcony', 'Swimming Pool', 'Laundry In Building', 'New Construction',
       'Terrace'],
      dtype='object')

In [76]:
len(feature_list)

22

In [78]:
X_train.head()

,bathrooms,bedrooms,Elevator,Hardwood Floors,Cats Allowed,Dogs Allowed,Doorman,Dishwasher,No Fee,Laundry in Building,...,Laundry in Unit,Roof Deck,Outdoor Space,Dining Room,High Speed Internet,Balcony,Swimming Pool,Laundry In Building,New Construction,Terrace
4,1.0,1,0,1,1,1,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0
6,1.0,2,1,1,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
9,1.0,2,1,1,0,0,1,1,0,1,...,1,0,0,0,0,0,0,0,0,0
10,1.5,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1.0,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [80]:
y_train.head()

4     2400
6     3800
9     3495
10    3000
15    2795
Name: price, dtype: int64

## 4) Реализация моделей — Линейная регрессия

### Реализуйте класс Python для алгоритма линейной регрессии с двумя базовыми методами — fit и predict. Используйте стохастический градиентный спуск (SGD) для поиска оптимальных весов модели. Для лучшего понимания рекомендуем реализовать отдельные версии алгоритма с аналитическим решением и нестохастическим градиентным спуском.

In [84]:
class LinearRegression_my():
    def __init__(self, method='Batch_Gradient_Descent', learning_rate=0.01, random_state=42, lambda1=0, lambda2=0, batch_size=32):
        self.method = method
        self.learning_rate = learning_rate
        self.weights = None
        self.bias = None
        self.random_state = random_state
        
        self.lambda1 = lambda1  
        self.lambda2 = lambda2
        self.batch_size = batch_size

    def _compute_gradients(self, X, y, y_pred, weights, m):
        dw = (2/m) * X.T @ (y_pred - y)
        db = (2/m) * np.sum(y_pred - y)
        
        if self.lambda2 > 0:
            dw += self.lambda2 * weights
        
        if self.lambda1 > 0:
            dw += self.lambda1 * np.sign(weights)
        
        return dw, db
    
    def fit(self, X, y, epochs=1000):
        np.random.seed(self.random_state)
        X = X.values if hasattr(X, 'values') else X
        y = y.values if hasattr(y, 'values') else y
        m, n = X.shape
        
        if self.method == 'normal_equation':
            X_with_bias = np.c_[np.ones(X.shape[0]), X]
            self.weights = np.linalg.pinv(X_with_bias.T @ X_with_bias) @ X_with_bias.T @ y
            self.bias = self.weights[0]
            self.weights = self.weights[1:]
            
        elif self.method == "Batch_Gradient_Descent":
            self.weights = np.zeros(n)
            self.bias = 0

            for epoch_num in tqdm(range(epochs)):
                y_pred = X @ self.weights + self.bias
                dw, db = self._compute_gradients(X, y, y_pred, self.weights, m)
                self.weights -= self.learning_rate * dw
                self.bias -= self.learning_rate * db
                
        elif self.method == "Stochastic_Gradient_Descent":
            self.weights = np.zeros(n)
            self.bias = 0

            for epoch_num in tqdm(range(epochs)):
                indices = np.random.permutation(m)
                X_shuffled = X[indices]
                y_shuffled = y[indices]   

                for i in range(m):
                    xi = X_shuffled[i]
                    yi = y_shuffled[i]
                    y_pred = xi @ self.weights + self.bias
                    
                    dw_single = 2 * xi * (y_pred - yi)  
                    db_single = 2 * (y_pred - yi)       
                    
                    if self.lambda2 > 0:
                        dw_single += self.lambda2 * self.weights
                    if self.lambda1 > 0:
                        dw_single += self.lambda1 * np.sign(self.weights)
                    
                    self.weights -= self.learning_rate * dw_single
                    self.bias -= self.learning_rate * db_single
                    
        elif self.method == "MiniBatch_Gradient_Descent":
            self.weights = np.zeros(n)
            self.bias = 0

            for epoch_num in tqdm(range(epochs)):
                indices = np.random.permutation(m)
                X_shuffled = X[indices]
                y_shuffled = y[indices]
                
                for i in range(0, m, self.batch_size):
                    X_batch = X_shuffled[i:i+self.batch_size]
                    y_batch = y_shuffled[i:i+self.batch_size]
                    batch_m = X_batch.shape[0]
                    
                    y_pred = X_batch @ self.weights + self.bias
                    dw, db = self._compute_gradients(X_batch, y_batch, y_pred, self.weights, batch_m)
                    
                    self.weights -= self.learning_rate * dw
                    self.bias -= self.learning_rate * db

    def predict(self, X):
        X = X.values if hasattr(X, 'values') else X
        return X @ self.weights + self.bias

### 2) Что такое детерменистическая модель? Сделайте SGD детерменистическим.

Batch_Gradient_Descent - детерменистическая модель (обучающаяся сразу на ряде разных данных)

### 3) Определите коэффициент R в квадрате (R2) и реализуйте функцию для его расчета.

$$R^2 = 1 - \frac{SS_{res}}{SS_{tot}}$$
$$SS_{\text{tot}} = \sum_{i=1}^{n} (y_i - \bar{y})^2$$
$$SS_{\text{res}} = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2$$
$n$ - количество наблюдений \
$y$ - истинное значение для i-го наблюдения​\
$\bar{y}$- предсказанное значение для i-го наблюдения\
$\hat{y}$ - среднее арифметическое истинных значений

In [90]:
LinearRegression_my.r2_score = lambda self, X, y: 1 - (np.sum((y - self.predict(X))**2) / np.sum((y - np.mean(y))**2))

### Делайте прогнозы с помощью вашего алгоритма и оцените модель с помощью метрик MAE, RMSE и R2.

In [92]:
LinearRegression_my.mae = lambda self, X, y: abs(y - self.predict(X)).mean()
LinearRegression_my.rmse = lambda self, X, y: np.sqrt(((y - self.predict(X))**2).mean())

### Инициализируйте LinearRegression() из sklearn.linear_model, подгоните модель и спрогнозируйте обучающую и тестовую части, как в предыдущем уроке. 
* Сравните показатели качества и убедитесь, что разница невелика (между вашими реализациями и sklearn).
* Сохраните метрики, как и в предыдущем уроке, в таблице со столбцами «модель», «обучение», «тест для таблицы MAE», «таблица RMSE» и «коэффициент R2».

In [95]:
result_MAE = pd.DataFrame(columns=["model", "train", "test", "metric"])
result_RMSE = pd.DataFrame(columns=["model", "train", "test", "metric"])
result_R2 = pd.DataFrame(columns=["model", "train", "test", "metric"])

def push_metrics(name, model, X_train, y_train, X_test, y_test, 
                result_MAE=result_MAE, result_RMSE=result_RMSE, result_R2=result_R2):
    
    if "Sklearn" in name:
        y_train_predict = model.predict(X_train)
        y_test_predict = model.predict(X_test)
        
        mae_train = mean_absolute_error(y_train, y_train_predict)
        mae_test = mean_absolute_error(y_test, y_test_predict)
        
        rmse_train = np.sqrt(mean_squared_error(y_train, y_train_predict))
        rmse_test = np.sqrt(mean_squared_error(y_test, y_test_predict))
        
        r2_train = r2_score(y_train, y_train_predict)
        r2_test = r2_score(y_test, y_test_predict)
        
    else:
        mae_train = model.mae(X_train, y_train)
        mae_test = model.mae(X_test, y_test)
        
        rmse_train = model.rmse(X_train, y_train)
        rmse_test = model.rmse(X_test, y_test)
        
        r2_train = model.r2_score(X_train, y_train)
        r2_test = model.r2_score(X_test, y_test)
    
    next_index_MAE = len(result_MAE)
    next_index_RMSE = len(result_RMSE)
    next_index_R2 = len(result_R2)
    
    result_MAE.loc[next_index_MAE] = [name, mae_train, mae_test, "MAE"]
    result_RMSE.loc[next_index_RMSE] = [name, rmse_train, rmse_test, "RMSE"]
    result_R2.loc[next_index_R2] = [name, r2_train, r2_test, "R2"]
    
    return result_MAE, result_RMSE, result_R2

In [96]:
models = {
    "Sklearn LinearRegression (Analytical)": LinearRegression(),
    "Sklearn SGDRegressor (Deterministic)": SGDRegressor(random_state=42, max_iter=1000, tol=0.01),
    "My LinearRegression (Normal Equation)": LinearRegression_my(method='normal_equation'),
    "My LinearRegression (Batch GD)": LinearRegression_my(method='Batch_Gradient_Descent'),
    "My LinearRegression (Stochastic GD)": LinearRegression_my(method='Stochastic_Gradient_Descent')
}

print("Сравнение различных реализаций линейной регрессии:")
print("=" * 70)

for name, model in models.items():
    print(f"\n=== {name} ===")
    
    model.fit(X_train, y_train)
    
    if "Sklearn" in name:
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)
        
        mae_train = mean_absolute_error(y_train, y_pred_train)
        rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
        r2_train = r2_score(y_train, y_pred_train)
        
        mae_test = mean_absolute_error(y_test, y_pred_test)
        rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
        r2_test = r2_score(y_test, y_pred_test)
        
    else:
        mae_train = model.mae(X_train, y_train)
        rmse_train = model.rmse(X_train, y_train)
        r2_train = model.r2_score(X_train, y_train)
        
        mae_test = model.mae(X_test, y_test)
        rmse_test = model.rmse(X_test, y_test)
        r2_test = model.r2_score(X_test, y_test)
    
    print(f"Тренировочные данные: MAE={mae_train:.4f}, RMSE={rmse_train:.4f}, R²={r2_train:.4f}")
    print(f"Тестовые данные:     MAE={mae_test:.4f}, RMSE={rmse_test:.4f}, R²={r2_test:.4f}")
    
    result_MAE, result_RMSE, result_R2 = push_metrics(name, model, X_train, y_train, X_test, y_test)

print("СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ:")
print("="*70)

print("\nМетрика MAE:")
print(result_MAE.round(4))

print("\nМетрика RMSE:")
print(result_RMSE.round(4))

print("\nМетрика R²:")
print(result_R2.round(4))

Сравнение различных реализаций линейной регрессии:
======================================================================

=== Sklearn LinearRegression (Analytical) ===
Тренировочные данные: MAE=708.7371, RMSE=1027.2629, R²=0.5803
Тестовые данные:     MAE=713.0153, RMSE=1213.5977, R²=0.4052

=== Sklearn SGDRegressor (Deterministic) ===
Тренировочные данные: MAE=707.1975, RMSE=1027.4142, R²=0.5801
Тестовые данные:     MAE=711.4176, RMSE=1212.1024, R²=0.4067

=== My LinearRegression (Normal Equation) ===
Тренировочные данные: MAE=708.7371, RMSE=1027.2629, R²=0.5803
Тестовые данные:     MAE=713.0153, RMSE=1213.5977, R²=0.4052

=== My LinearRegression (Batch GD) ===

100%|██████████████████████████████████████| 1000/1000 [00:01<00:00, 607.73it/s]

Тренировочные данные: MAE=708.9878, RMSE=1028.6358, R²=0.5791
Тестовые данные:     MAE=713.1200, RMSE=1204.7987, R²=0.4138

=== My LinearRegression (Stochastic GD) ===

100%|███████████████████████████████████████| 1000/1000 [03:35<00:00,  4.65it/s]

Тренировочные данные: MAE=863.7366, RMSE=1269.1302, R²=0.3594
Тестовые данные:     MAE=865.0665, RMSE=1382.8212, R²=0.2277
СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ:
======================================================================

Метрика MAE:
                                   model     train      test metric
0  Sklearn LinearRegression (Analytical)  708.7371  713.0153    MAE
1   Sklearn SGDRegressor (Deterministic)  707.1975  711.4176    MAE
2  My LinearRegression (Normal Equation)  708.7371  713.0153    MAE
3         My LinearRegression (Batch GD)  708.9878  713.1200    MAE
4    My LinearRegression (Stochastic GD)  863.7366  865.0665    MAE

Метрика RMSE:
                                   model      train       test metric
0  Sklearn LinearRegression (Analytical)  1027.2629  1213.5977   RMSE
1   Sklearn SGDRegressor (Deterministic)  1027.4142  1212.1024   RMSE
2  My LinearRegression (Normal Equation)  1027.2629  1213.5977   RMSE
3         My LinearRegression (Batch GD)  1028.6358  1204.7987   RMSE
4    My LinearRegression (Stochastic GD)  1269.1302  1382.8212   RMSE

Метрика R²:
                                   model   train    test metric
0  Sklearn LinearRegression (Analytical)  0.5803  0.4052     R2
1   Sklearn SGDRegressor (Deterministic)  0.5801  0.4067     R2
2  My LinearRegression (Normal Equation)  0.5803  0.4052     R2
3         My LinearRegression (Batch GD)  0.5791  0.4138     R2
4    My LinearRegression (Stochastic GD)  0.3594  0.2277     R2

## 5. Реализация регуляризованных моделей — Ridge, Lasso, ElasticNet

In [98]:
models = {
    "My Batch GD (L1)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0.01, lambda2=0),
    "My Batch GD (L2)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0, lambda2=0.01),
    "My Batch GD (L1+L2)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0.01, lambda2=0.01),
    
    "My Stochastic GD (L1)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0.01, lambda2=0),
    "My Stochastic GD (L2)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0, lambda2=0.01),
    "My Stochastic GD (L1+L2)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0.01, lambda2=0.01),
    
    "Sklearn Lasso": Lasso(alpha=0.01, random_state=42),
    "Sklearn Ridge": Ridge(alpha=0.01, random_state=42),
    "Sklearn ElasticNet": ElasticNet(alpha=0.01, l1_ratio=0.5, random_state=42)
}

print("Сравнение различных реализаций линейной регрессии:")
print("=" * 70)

for name, model in models.items():
    print(f"\n=== {name} ===")
    
    model.fit(X_train, y_train)
    
    if "Sklearn" in name:
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)
        
        mae_train = mean_absolute_error(y_train, y_pred_train)
        rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
        r2_train = r2_score(y_train, y_pred_train)
        
        mae_test = mean_absolute_error(y_test, y_pred_test)
        rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
        r2_test = r2_score(y_test, y_pred_test)
        
    else:
        mae_train = model.mae(X_train, y_train)
        rmse_train = model.rmse(X_train, y_train)
        r2_train = model.r2_score(X_train, y_train)
        
        mae_test = model.mae(X_test, y_test)
        rmse_test = model.rmse(X_test, y_test)
        r2_test = model.r2_score(X_test, y_test)
    
    print(f"Тренировочные данные: MAE={mae_train:.4f}, RMSE={rmse_train:.4f}, R²={r2_train:.4f}")
    print(f"Тестовые данные:     MAE={mae_test:.4f}, RMSE={rmse_test:.4f}, R²={r2_test:.4f}")
    
    result_MAE, result_RMSE, result_R2 = push_metrics(name, model, X_train, y_train, X_test, y_test)

print("СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ:")
print("="*70)

print("\nМетрика MAE:")
print(result_MAE.round(4))

print("\nМетрика RMSE:")
print(result_RMSE.round(4))

print("\nМетрика R²:")
print(result_R2.round(4))

Сравнение различных реализаций линейной регрессии:
======================================================================

=== My Batch GD (L1) ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1077.84it/s]

Тренировочные данные: MAE=708.9874, RMSE=1028.6374, R²=0.5791
Тестовые данные:     MAE=713.1195, RMSE=1204.7978, R²=0.4138

=== My Batch GD (L2) ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1131.30it/s]

Тренировочные данные: MAE=708.8934, RMSE=1029.2567, R²=0.5786
Тестовые данные:     MAE=712.9005, RMSE=1198.0668, R²=0.4203

=== My Batch GD (L1+L2) ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1099.86it/s]

Тренировочные данные: MAE=708.8934, RMSE=1029.2586, R²=0.5786
Тестовые данные:     MAE=712.9004, RMSE=1198.0662, R²=0.4203

=== My Stochastic GD (L1) ===

100%|███████████████████████████████████████| 1000/1000 [04:45<00:00,  3.50it/s]

Тренировочные данные: MAE=863.7421, RMSE=1269.1439, R²=0.3593
Тестовые данные:     MAE=865.0710, RMSE=1382.8301, R²=0.2277

=== My Stochastic GD (L2) ===

100%|███████████████████████████████████████| 1000/1000 [04:25<00:00,  3.77it/s]

Тренировочные данные: MAE=862.1839, RMSE=1271.9539, R²=0.3565
Тестовые данные:     MAE=863.2878, RMSE=1377.5579, R²=0.2336

=== My Stochastic GD (L1+L2) ===

100%|███████████████████████████████████████| 1000/1000 [10:46<00:00,  1.55it/s]

Тренировочные данные: MAE=862.1910, RMSE=1271.9699, R²=0.3565
Тестовые данные:     MAE=863.2942, RMSE=1377.5693, R²=0.2336

=== Sklearn Lasso ===
Тренировочные данные: MAE=708.7313, RMSE=1027.2629, R²=0.5803
Тестовые данные:     MAE=713.0093, RMSE=1213.5945, R²=0.4052

=== Sklearn Ridge ===
Тренировочные данные: MAE=708.7371, RMSE=1027.2629, R²=0.5803
Тестовые данные:     MAE=713.0153, RMSE=1213.5973, R²=0.4052

=== Sklearn ElasticNet ===
Тренировочные данные: MAE=708.2902, RMSE=1027.5323, R²=0.5800
Тестовые данные:     MAE=712.3643, RMSE=1204.0805, R²=0.4145
СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ:
======================================================================

Метрика MAE:
                                    model     train      test metric
0   Sklearn LinearRegression (Analytical)  708.7371  713.0153    MAE
1    Sklearn SGDRegressor (Deterministic)  707.1975  711.4176    MAE
2   My LinearRegression (Normal Equation)  708.7371  713.0153    MAE
3          My LinearRegression (Batch GD)  708.9878  713.1200    MAE
4     My LinearRegression (Stochastic GD)  863.7366  865.0665    MAE
5                        My Batch GD (L1)  708.9874  713.1195    MAE
6                        My Batch GD (L2)  708.8934  712.9005    MAE
7                     My Batch GD (L1+L2)  708.8934  712.9004    MAE
8                   My Stochastic GD (L1)  863.7421  865.0710    MAE
9                   My Stochastic GD (L2)  862.1839  863.2878    MAE
10               My Stochastic GD (L1+L2)  862.1910  863.2942    MAE
11                          Sklearn Lasso  708.7313  713.0093    MAE
12                          Sklearn Ridge  708.7371  713.0153    MAE
13                     Sklearn ElasticNet  708.2902  712.3643    MAE

Метрика RMSE:
                                    model      train       test metric
0   Sklearn LinearRegression (Analytical)  1027.2629  1213.5977   RMSE
1    Sklearn SGDRegressor (Deterministic)  1027.4142  1212.1024   RMSE
2   My LinearRegression (Normal Equation)  1027.2629  1213.5977   RMSE
3          My LinearRegression (Batch GD)  1028.6358  1204.7987   RMSE
4     My LinearRegression (Stochastic GD)  1269.1302  1382.8212   RMSE
5                        My Batch GD (L1)  1028.6374  1204.7978   RMSE
6                        My Batch GD (L2)  1029.2567  1198.0668   RMSE
7                     My Batch GD (L1+L2)  1029.2586  1198.0662   RMSE
8                   My Stochastic GD (L1)  1269.1439  1382.8301   RMSE
9                   My Stochastic GD (L2)  1271.9539  1377.5579   RMSE
10               My Stochastic GD (L1+L2)  1271.9699  1377.5693   RMSE
11                          Sklearn Lasso  1027.2629  1213.5945   RMSE
12                          Sklearn Ridge  1027.2629  1213.5973   RMSE
13                     Sklearn ElasticNet  1027.5323  1204.0805   RMSE

Метрика R²:
                                    model   train    test metric
0   Sklearn LinearRegression (Analytical)  0.5803  0.4052     R2
1    Sklearn SGDRegressor (Deterministic)  0.5801  0.4067     R2
2   My LinearRegression (Normal Equation)  0.5803  0.4052     R2
3          My LinearRegression (Batch GD)  0.5791  0.4138     R2
4     My LinearRegression (Stochastic GD)  0.3594  0.2277     R2
5                        My Batch GD (L1)  0.5791  0.4138     R2
6                        My Batch GD (L2)  0.5786  0.4203     R2
7                     My Batch GD (L1+L2)  0.5786  0.4203     R2
8                   My Stochastic GD (L1)  0.3593  0.2277     R2
9                   My Stochastic GD (L2)  0.3565  0.2336     R2
10               My Stochastic GD (L1+L2)  0.3565  0.2336     R2
11                          Sklearn Lasso  0.5803  0.4052     R2
12                          Sklearn Ridge  0.5803  0.4052     R2
13                     Sklearn ElasticNet  0.5800  0.4145     R2

## Нормализация признаков

### 1. Сначала напишите несколько примеров того, почему и где нормализация признаков обязательна, и наоборот.

1) в первую очередь в методах на основе растояний (KNN)
2) при вычислении градиентов (все рассмотренные методы)
3) численная стабильность

### 2.Рассмотрим первый из классических методов нормализации — MinMaxScaler. Запишите математическую формулу для этого метода.

$$X_{scaled} = (X - X_{min}) / (X_{max} - X_{min})$$

### 3. Реализуйте собственную функцию или класс для нормализации признаков MinMaxScaler.

In [107]:
class MyMinMaxScaler:
    def __init__(self):
        self.min_ = None
        self.max_ = None
        self.data_range_ = None
    
    def fit(self, X):
        self.min_ = np.min(X, axis=0)
        self.max_ = np.max(X, axis=0)
        self.data_range_ = self.max_ - self.min_
        return self
    
    def transform(self, X):
        if self.min_ is None or self.max_ is None:
            raise ValueError("Scaler must be fitted before transformation")
        data_range = self.data_range_.copy()
        data_range[data_range == 0] = 1
        
        return (X - self.min_) / data_range
    
    def fit_transform(self, X):
        return self.fit(X).transform(X)

### 5. Сравните нормализацию признаков с вашим собственным методом и с помощью sklearn.

In [109]:
my_scaler = MyMinMaxScaler()
X_my = my_scaler.fit_transform(X_train)

sklearn_scaler = MinMaxScaler()
X_sklearn = sklearn_scaler.fit_transform(X_train)

np.allclose(X_my, X_sklearn, atol=1e-5)

True

### 6. Повторите шаги от b до e для другого метода нормализации StandardScaler.

$$X_{\text{scaled}} = \frac{X - \mu}{\sigma}$$
$\mu_j = \frac{1}{n} \sum_{i=1}^{n} X_{ij}$ - среднее j-го признака

$\sigma_j = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (X_{ij} - \mu_j)^2}$ - стандартное отклонение j-го признака

In [112]:
class MyStandardScaler:
    def __init__(self):
        self.mean_ = None
        self.scale_ = None  
    
    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.scale_ = np.std(X, axis=0)
        return self
    
    def transform(self, X):
        if self.mean_ is None or self.scale_ is None:
            raise ValueError("Scaler must be fitted before transformation")
        
        scale = self.scale_.copy()
        scale[scale == 0] = 1
        
        return (X - self.mean_) / scale
    
    def fit_transform(self, X):
        return self.fit(X).transform(X)

In [113]:
my_scaler = MyStandardScaler()
X_my = my_scaler.fit_transform(X_train)

sklearn_scaler = StandardScaler()
X_sklearn = sklearn_scaler.fit_transform(X_train)

np.allclose(X_my, X_sklearn, atol=1e-5)

True

## 7. Подгонка пользовательских и sklearn-моделей под нормализованные данные

In [115]:
my_minmax_scaler = MyMinMaxScaler()
my_std_scaler = MyStandardScaler()
sklearn_minmax_scaler = MinMaxScaler()
sklearn_std_scaler = StandardScaler()

X_train_my_minmax = my_minmax_scaler.fit_transform(X_train)
X_test_my_minmax = my_minmax_scaler.transform(X_test)
X_train_my_std = my_std_scaler.fit_transform(X_train)
X_test_my_std = my_std_scaler.transform(X_test)

X_train_sklearn_minmax = sklearn_minmax_scaler.fit_transform(X_train)
X_test_sklearn_minmax = sklearn_minmax_scaler.transform(X_test)
X_train_sklearn_std = sklearn_std_scaler.fit_transform(X_train)
X_test_sklearn_std = sklearn_std_scaler.transform(X_test)

models = {
    "My Batch GD (L1)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0.01, lambda2=0),
    "My Batch GD (L2)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0, lambda2=0.01),
    "My Batch GD (L1+L2)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0.01, lambda2=0.01),
    
    "My Stochastic GD (L1)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0.01, lambda2=0),
    "My Stochastic GD (L2)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0, lambda2=0.01),
    "My Stochastic GD (L1+L2)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0.01, lambda2=0.01),
    
    "Sklearn Lasso": Lasso(alpha=0.01, random_state=42),
    "Sklearn Ridge": Ridge(alpha=0.01, random_state=42),
    "Sklearn ElasticNet": ElasticNet(alpha=0.01, l1_ratio=0.5, random_state=42)
}

print("Сравнение различных реализаций линейной регрессии:")
print("=" * 70)

for scaler in [0, 1]:  
    for name, model in models.items():
        current_name = name 
        if scaler:
            current_name += " norm = std"  
        else:
            current_name += " norm = minmax"
            
        print(f"\n=== {current_name} ===")
        
        if "My" in name:
            # Свои модели на своих нормализаторах
            if scaler:  # std
                X_train_curr = X_train_my_std  
                X_test_curr = X_test_my_std
            else:  # minmax
                X_train_curr = X_train_my_minmax
                X_test_curr = X_test_my_minmax
        else:
            # Sklearn модели на sklearn нормализаторах  
            if scaler:  # std
                X_train_curr = X_train_sklearn_std  
                X_test_curr = X_test_sklearn_std
            else:  # minmax
                X_train_curr = X_train_sklearn_minmax
                X_test_curr = X_test_sklearn_minmax
        
        model.fit(X_train_curr, y_train)
        
        if "Sklearn" in name:
            y_pred_train = model.predict(X_train_curr)
            y_pred_test = model.predict(X_test_curr)
            
            mae_train = mean_absolute_error(y_train, y_pred_train)
            rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
            r2_train = r2_score(y_train, y_pred_train)
            
            mae_test = mean_absolute_error(y_test, y_pred_test)
            rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
            r2_test = r2_score(y_test, y_pred_test)
            
        else:
            mae_train = model.mae(X_train_curr, y_train)
            rmse_train = model.rmse(X_train_curr, y_train)
            r2_train = model.r2_score(X_train_curr, y_train)
            
            mae_test = model.mae(X_test_curr, y_test)
            rmse_test = model.rmse(X_test_curr, y_test)
            r2_test = model.r2_score(X_test_curr, y_test)
        
        print(f"Тренировочные данные: MAE={mae_train:.4f}, RMSE={rmse_train:.4f}, R²={r2_train:.4f}")
        print(f"Тестовые данные:     MAE={mae_test:.4f}, RMSE={rmse_test:.4f}, R²={r2_test:.4f}")
        
        result_MAE, result_RMSE, result_R2 = push_metrics(current_name, model, X_train_curr, y_train, X_test_curr, y_test)

Сравнение различных реализаций линейной регрессии:
======================================================================

=== My Batch GD (L1) norm = minmax ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1056.54it/s]

Тренировочные данные: MAE=885.3194, RMSE=1278.4919, R²=0.3499
Тестовые данные:     MAE=884.0764, RMSE=1269.7893, R²=0.3488

=== My Batch GD (L2) norm = minmax ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1027.92it/s]

Тренировочные данные: MAE=891.2906, RMSE=1286.1148, R²=0.3421
Тестовые данные:     MAE=889.9334, RMSE=1277.1397, R²=0.3413

=== My Batch GD (L1+L2) norm = minmax ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1017.83it/s]

Тренировочные данные: MAE=891.2964, RMSE=1286.1221, R²=0.3421
Тестовые данные:     MAE=889.9392, RMSE=1277.1468, R²=0.3413

=== My Stochastic GD (L1) norm = minmax ===

100%|███████████████████████████████████████| 1000/1000 [04:53<00:00,  3.40it/s]

Тренировочные данные: MAE=742.4449, RMSE=1094.1328, R²=0.5238
Тестовые данные:     MAE=745.7200, RMSE=1266.2137, R²=0.3525

=== My Stochastic GD (L2) norm = minmax ===

100%|███████████████████████████████████████| 1000/1000 [04:27<00:00,  3.73it/s]

Тренировочные данные: MAE=773.3136, RMSE=1190.0275, R²=0.4367
Тестовые данные:     MAE=774.3773, RMSE=1193.6149, R²=0.4246

=== My Stochastic GD (L1+L2) norm = minmax ===

100%|███████████████████████████████████████| 1000/1000 [05:40<00:00,  2.94it/s]

Тренировочные данные: MAE=773.3174, RMSE=1190.0497, R²=0.4367
Тестовые данные:     MAE=774.3809, RMSE=1193.6328, R²=0.4246

=== Sklearn Lasso norm = minmax ===
Тренировочные данные: MAE=708.7330, RMSE=1027.2629, R²=0.5803
Тестовые данные:     MAE=713.0088, RMSE=1213.4736, R²=0.4053

=== Sklearn Ridge norm = minmax ===
Тренировочные данные: MAE=708.7377, RMSE=1027.2629, R²=0.5803
Тестовые данные:     MAE=713.0152, RMSE=1213.5483, R²=0.4052

=== Sklearn ElasticNet norm = minmax ===
Тренировочные данные: MAE=768.8756, RMSE=1127.7674, R²=0.4941
Тестовые данные:     MAE=769.8145, RMSE=1134.5994, R²=0.4801

=== My Batch GD (L1) norm = std ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1051.15it/s]

Тренировочные данные: MAE=708.7641, RMSE=1027.2784, R²=0.5803
Тестовые данные:     MAE=713.0482, RMSE=1213.6027, R²=0.4052

=== My Batch GD (L2) norm = std ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1055.22it/s]

Тренировочные данные: MAE=708.6524, RMSE=1027.2912, R²=0.5802
Тестовые данные:     MAE=712.8974, RMSE=1212.2130, R²=0.4066

=== My Batch GD (L1+L2) norm = std ===

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1029.66it/s]

Тренировочные данные: MAE=708.6516, RMSE=1027.2913, R²=0.5802
Тестовые данные:     MAE=712.8965, RMSE=1212.2131, R²=0.4066

=== My Stochastic GD (L1) norm = std ===

100%|███████████████████████████████████████| 1000/1000 [04:51<00:00,  3.43it/s]

Тренировочные данные: MAE=785.6379, RMSE=1124.9997, R²=0.4966
Тестовые данные:     MAE=788.4443, RMSE=1243.1291, R²=0.3759

=== My Stochastic GD (L2) norm = std ===

100%|███████████████████████████████████████| 1000/1000 [04:30<00:00,  3.69it/s]

Тренировочные данные: MAE=784.9306, RMSE=1124.8753, R²=0.4967
Тестовые данные:     MAE=787.7481, RMSE=1242.0094, R²=0.3770

=== My Stochastic GD (L1+L2) norm = std ===

100%|███████████████████████████████████████| 1000/1000 [05:40<00:00,  2.94it/s]

Тренировочные данные: MAE=784.9258, RMSE=1124.8717, R²=0.4967
Тестовые данные:     MAE=787.7435, RMSE=1242.0068, R²=0.3770

=== Sklearn Lasso norm = std ===
Тренировочные данные: MAE=708.7350, RMSE=1027.2629, R²=0.5803
Тестовые данные:     MAE=713.0132, RMSE=1213.5976, R²=0.4052

=== Sklearn Ridge norm = std ===
Тренировочные данные: MAE=708.7371, RMSE=1027.2629, R²=0.5803
Тестовые данные:     MAE=713.0153, RMSE=1213.5976, R²=0.4052

=== Sklearn ElasticNet norm = std ===
Тренировочные данные: MAE=708.6224, RMSE=1027.2737, R²=0.5803
Тестовые данные:     MAE=712.8605, RMSE=1212.2041, R²=0.4066

In [116]:
print("СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ:")
print("="*70)

print("\nМетрика MAE:")
print(result_MAE.round(4))

print("\nМетрика RMSE:")
print(result_RMSE.round(4))

print("\nМетрика R²:")
print(result_R2.round(4))

СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ:
======================================================================

Метрика MAE:
                                     model     train      test metric
0    Sklearn LinearRegression (Analytical)  708.7371  713.0153    MAE
1     Sklearn SGDRegressor (Deterministic)  707.1975  711.4176    MAE
2    My LinearRegression (Normal Equation)  708.7371  713.0153    MAE
3           My LinearRegression (Batch GD)  708.9878  713.1200    MAE
4      My LinearRegression (Stochastic GD)  863.7366  865.0665    MAE
5                         My Batch GD (L1)  708.9874  713.1195    MAE
6                         My Batch GD (L2)  708.8934  712.9005    MAE
7                      My Batch GD (L1+L2)  708.8934  712.9004    MAE
8                    My Stochastic GD (L1)  863.7421  865.0710    MAE
9                    My Stochastic GD (L2)  862.1839  863.2878    MAE
10                My Stochastic GD (L1+L2)  862.1910  863.2942    MAE
11                           Sklearn Lasso  708.7313  713.0093    MAE
12                           Sklearn Ridge  708.7371  713.0153    MAE
13                      Sklearn ElasticNet  708.2902  712.3643    MAE
14          My Batch GD (L1) norm = minmax  885.3194  884.0764    MAE
15          My Batch GD (L2) norm = minmax  891.2906  889.9334    MAE
16       My Batch GD (L1+L2) norm = minmax  891.2964  889.9392    MAE
17     My Stochastic GD (L1) norm = minmax  742.4449  745.7200    MAE
18     My Stochastic GD (L2) norm = minmax  773.3136  774.3773    MAE
19  My Stochastic GD (L1+L2) norm = minmax  773.3174  774.3809    MAE
20             Sklearn Lasso norm = minmax  708.7330  713.0088    MAE
21             Sklearn Ridge norm = minmax  708.7377  713.0152    MAE
22        Sklearn ElasticNet norm = minmax  768.8756  769.8145    MAE
23             My Batch GD (L1) norm = std  708.7641  713.0482    MAE
24             My Batch GD (L2) norm = std  708.6524  712.8974    MAE
25          My Batch GD (L1+L2) norm = std  708.6516  712.8965    MAE
26        My Stochastic GD (L1) norm = std  785.6379  788.4443    MAE
27        My Stochastic GD (L2) norm = std  784.9306  787.7481    MAE
28     My Stochastic GD (L1+L2) norm = std  784.9258  787.7435    MAE
29                Sklearn Lasso norm = std  708.7350  713.0132    MAE
30                Sklearn Ridge norm = std  708.7371  713.0153    MAE
31           Sklearn ElasticNet norm = std  708.6224  712.8605    MAE

Метрика RMSE:
                                     model      train       test metric
0    Sklearn LinearRegression (Analytical)  1027.2629  1213.5977   RMSE
1     Sklearn SGDRegressor (Deterministic)  1027.4142  1212.1024   RMSE
2    My LinearRegression (Normal Equation)  1027.2629  1213.5977   RMSE
3           My LinearRegression (Batch GD)  1028.6358  1204.7987   RMSE
4      My LinearRegression (Stochastic GD)  1269.1302  1382.8212   RMSE
5                         My Batch GD (L1)  1028.6374  1204.7978   RMSE
6                         My Batch GD (L2)  1029.2567  1198.0668   RMSE
7                      My Batch GD (L1+L2)  1029.2586  1198.0662   RMSE
8                    My Stochastic GD (L1)  1269.1439  1382.8301   RMSE
9                    My Stochastic GD (L2)  1271.9539  1377.5579   RMSE
10                My Stochastic GD (L1+L2)  1271.9699  1377.5693   RMSE
11                           Sklearn Lasso  1027.2629  1213.5945   RMSE
12                           Sklearn Ridge  1027.2629  1213.5973   RMSE
13                      Sklearn ElasticNet  1027.5323  1204.0805   RMSE
14          My Batch GD (L1) norm = minmax  1278.4919  1269.7893   RMSE
15          My Batch GD (L2) norm = minmax  1286.1148  1277.1397   RMSE
16       My Batch GD (L1+L2) norm = minmax  1286.1221  1277.1468   RMSE
17     My Stochastic GD (L1) norm = minmax  1094.1328  1266.2137   RMSE
18     My Stochastic GD (L2) norm = minmax  1190.0275  1193.6149   RMSE
19  My Stochastic GD (L1+L2) norm = minmax  1190.0497  1193.6328   RMSE
20             Sklearn Lasso norm = minmax  1027.2629  1213.4736   RMSE
21             Sklearn Ridge norm = minmax  1027.2629  1213.5483   RMSE
22        Sklearn ElasticNet norm = minmax  1127.7674  1134.5994   RMSE
23             My Batch GD (L1) norm = std  1027.2784  1213.6027   RMSE
24             My Batch GD (L2) norm = std  1027.2912  1212.2130   RMSE
25          My Batch GD (L1+L2) norm = std  1027.2913  1212.2131   RMSE
26        My Stochastic GD (L1) norm = std  1124.9997  1243.1291   RMSE
27        My Stochastic GD (L2) norm = std  1124.8753  1242.0094   RMSE
28     My Stochastic GD (L1+L2) norm = std  1124.8717  1242.0068   RMSE
29                Sklearn Lasso norm = std  1027.2629  1213.5976   RMSE
30                Sklearn Ridge norm = std  1027.2629  1213.5976   RMSE
31           Sklearn ElasticNet norm = std  1027.2737  1212.2041   RMSE

Метрика R²:
                                     model   train    test metric
0    Sklearn LinearRegression (Analytical)  0.5803  0.4052     R2
1     Sklearn SGDRegressor (Deterministic)  0.5801  0.4067     R2
2    My LinearRegression (Normal Equation)  0.5803  0.4052     R2
3           My LinearRegression (Batch GD)  0.5791  0.4138     R2
4      My LinearRegression (Stochastic GD)  0.3594  0.2277     R2
5                         My Batch GD (L1)  0.5791  0.4138     R2
6                         My Batch GD (L2)  0.5786  0.4203     R2
7                      My Batch GD (L1+L2)  0.5786  0.4203     R2
8                    My Stochastic GD (L1)  0.3593  0.2277     R2
9                    My Stochastic GD (L2)  0.3565  0.2336     R2
10                My Stochastic GD (L1+L2)  0.3565  0.2336     R2
11                           Sklearn Lasso  0.5803  0.4052     R2
12                           Sklearn Ridge  0.5803  0.4052     R2
13                      Sklearn ElasticNet  0.5800  0.4145     R2
14          My Batch GD (L1) norm = minmax  0.3499  0.3488     R2
15          My Batch GD (L2) norm = minmax  0.3421  0.3413     R2
16       My Batch GD (L1+L2) norm = minmax  0.3421  0.3413     R2
17     My Stochastic GD (L1) norm = minmax  0.5238  0.3525     R2
18     My Stochastic GD (L2) norm = minmax  0.4367  0.4246     R2
19  My Stochastic GD (L1+L2) norm = minmax  0.4367  0.4246     R2
20             Sklearn Lasso norm = minmax  0.5803  0.4053     R2
21             Sklearn Ridge norm = minmax  0.5803  0.4052     R2
22        Sklearn ElasticNet norm = minmax  0.4941  0.4801     R2
23             My Batch GD (L1) norm = std  0.5803  0.4052     R2
24             My Batch GD (L2) norm = std  0.5802  0.4066     R2
25          My Batch GD (L1+L2) norm = std  0.5802  0.4066     R2
26        My Stochastic GD (L1) norm = std  0.4966  0.3759     R2
27        My Stochastic GD (L2) norm = std  0.4967  0.3770     R2
28     My Stochastic GD (L1+L2) norm = std  0.4967  0.3770     R2
29                Sklearn Lasso norm = std  0.5803  0.4052     R2
30                Sklearn Ridge norm = std  0.5803  0.4052     R2
31           Sklearn ElasticNet norm = std  0.5803  0.4066     R2

## 8. Модели переобучения

In [118]:
X_train_copy = X_train.copy()
X_test_copy = X_test.copy()

selected_features = ["bathrooms", "bedrooms"]
X_train_selected = X_train[selected_features]
X_test_selected = X_test[selected_features]

poly = PolynomialFeatures(degree=10, include_bias=False)

X_train_poly = poly.fit_transform(X_train_selected)
X_test_poly = poly.transform(X_test_selected)

X_train = pd.DataFrame(X_train_poly, 
                      columns=poly.get_feature_names_out(selected_features),
                      index=X_train.index)

X_test = pd.DataFrame(X_test_poly, 
                     columns=poly.get_feature_names_out(selected_features),
                     index=X_test.index)

In [119]:
X_train.head()

,bathrooms,bedrooms,bathrooms^2,bathrooms bedrooms,bedrooms^2,bathrooms^3,bathrooms^2 bedrooms,bathrooms bedrooms^2,bedrooms^3,bathrooms^4,...,bathrooms^9 bedrooms,bathrooms^8 bedrooms^2,bathrooms^7 bedrooms^3,bathrooms^6 bedrooms^4,bathrooms^5 bedrooms^5,bathrooms^4 bedrooms^6,bathrooms^3 bedrooms^7,bathrooms^2 bedrooms^8,bathrooms bedrooms^9,bedrooms^10
4,1.0,1.0,1.00,1.0,1.0,1.000,1.00,1.0,1.0,1.0000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.0000,1.000,1.00,1.0,1.0
6,1.0,2.0,1.00,2.0,4.0,1.000,2.00,4.0,8.0,1.0000,...,2.000000,4.000000,8.000000,16.000000,32.00000,64.0000,128.000,256.00,512.0,1024.0
9,1.0,2.0,1.00,2.0,4.0,1.000,2.00,4.0,8.0,1.0000,...,2.000000,4.000000,8.000000,16.000000,32.00000,64.0000,128.000,256.00,512.0,1024.0
10,1.5,3.0,2.25,4.5,9.0,3.375,6.75,13.5,27.0,5.0625,...,115.330078,230.660156,461.320312,922.640625,1845.28125,3690.5625,7381.125,14762.25,29524.5,59049.0
15,1.0,0.0,1.00,0.0,0.0,1.000,0.00,0.0,0.0,1.0000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.000,0.00,0.0,0.0

In [120]:
X_test.head()

,bathrooms,bedrooms,bathrooms^2,bathrooms bedrooms,bedrooms^2,bathrooms^3,bathrooms^2 bedrooms,bathrooms bedrooms^2,bedrooms^3,bathrooms^4,...,bathrooms^9 bedrooms,bathrooms^8 bedrooms^2,bathrooms^7 bedrooms^3,bathrooms^6 bedrooms^4,bathrooms^5 bedrooms^5,bathrooms^4 bedrooms^6,bathrooms^3 bedrooms^7,bathrooms^2 bedrooms^8,bathrooms bedrooms^9,bedrooms^10
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,1.0,2.0,1.0,2.0,4.0,1.0,2.0,4.0,8.0,1.0,...,2.0,4.0,8.0,16.0,32.0,64.0,128.0,256.0,512.0,1024.0
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,2.0,1.0,2.0,4.0,1.0,2.0,4.0,8.0,1.0,...,2.0,4.0,8.0,16.0,32.0,64.0,128.0,256.0,512.0,1024.0
5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [121]:
result_MAE_2 = pd.DataFrame(columns=["model", "train", "test", "metric"])
result_RMSE_2 = pd.DataFrame(columns=["model", "train", "test", "metric"])
result_R2_2 = pd.DataFrame(columns=["model", "train", "test", "metric"])

In [122]:
models = {
    "Sklearn LinearRegression (Analytical)": LinearRegression(),
    "Sklearn SGDRegressor (Deterministic)": SGDRegressor(random_state=42, max_iter=1000, tol=0.01),
    "My LinearRegression (Normal Equation)": LinearRegression_my(method='normal_equation'),
    "My LinearRegression (Batch GD)": LinearRegression_my(method='Batch_Gradient_Descent'),
    "My LinearRegression (Stochastic GD)": LinearRegression_my(method='Stochastic_Gradient_Descent')
}

print("Сравнение различных реализаций линейной регрессии:")
print("=" * 70)

for name, model in models.items():
    print(f"\n=== {name} ===")
    
    model.fit(X_train, y_train)
    
    if "Sklearn" in name:
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)
        
        mae_train = mean_absolute_error(y_train, y_pred_train)
        rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
        r2_train = r2_score(y_train, y_pred_train)
        
        mae_test = mean_absolute_error(y_test, y_pred_test)
        rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
        r2_test = r2_score(y_test, y_pred_test)
        
    else:
        mae_train = model.mae(X_train, y_train)
        rmse_train = model.rmse(X_train, y_train)
        r2_train = model.r2_score(X_train, y_train)
        
        mae_test = model.mae(X_test, y_test)
        rmse_test = model.rmse(X_test, y_test)
        r2_test = model.r2_score(X_test, y_test)
    
    print(f"Тренировочные данные: MAE={mae_train:.4f}, RMSE={rmse_train:.4f}, R²={r2_train:.4f}")
    print(f"Тестовые данные:     MAE={mae_test:.4f}, RMSE={rmse_test:.4f}, R²={r2_test:.4f}")
    
    result_MAE_2, result_RMSE_2, result_R2_2 = push_metrics(name, model, X_train, y_train, X_test, y_test, 
                result_MAE=result_MAE_2, result_RMSE=result_RMSE_2, result_R2=result_R2_2)

Сравнение различных реализаций линейной регрессии:
======================================================================

=== Sklearn LinearRegression (Analytical) ===
Тренировочные данные: MAE=753.6761, RMSE=1070.5990, R²=0.5441
Тестовые данные:     MAE=2779448219069931520.0000, RMSE=751885683818116939776.0000, R²=-228312493787480248588617767563821056.0000

=== Sklearn SGDRegressor (Deterministic) ===
Тренировочные данные: MAE=45913497738466859941888.0000, RMSE=1850981936658247892074496.0000, R²=-1362737171929276531867157798486587213873152.0000
Тестовые данные:     MAE=51345165678059063434831454011392.0000, RMSE=13889696444784668619017939090145280.0000, R²=-77913292093887836214768287431339499515090661112787716676780032.0000

=== My LinearRegression (Normal Equation) ===
Тренировочные данные: MAE=1185.4171, RMSE=1512.6230, R²=0.0899
Тестовые данные:     MAE=105744962167220.5000, RMSE=28605718480608872.0000, R²=-330469791721614306250326016.0000

=== My LinearRegression (Batch GD) ===

  1%|▍                                       | 12/1000 [00:00<00:08, 119.81it/s]/tmp/ipykernel_34276/915070416.py:14: RuntimeWarning: overflow encountered in matmul
  dw = (2/m) * X.T @ (y_pred - y)
/tmp/ipykernel_34276/915070416.py:42: RuntimeWarning: overflow encountered in matmul
  y_pred = X @ self.weights + self.bias
/tmp/ipykernel_34276/915070416.py:42: RuntimeWarning: invalid value encountered in matmul
  y_pred = X @ self.weights + self.bias
100%|██████████████████████████████████████| 1000/1000 [00:06<00:00, 147.97it/s]

Тренировочные данные: MAE=nan, RMSE=nan, R²=1.0000
Тестовые данные:     MAE=nan, RMSE=nan, R²=1.0000

=== My LinearRegression (Stochastic GD) ===

  0%|                                                  | 0/1000 [00:00<?, ?it/s]/tmp/ipykernel_34276/915070416.py:61: RuntimeWarning: overflow encountered in multiply
  dw_single = 2 * xi * (y_pred - yi)
/tmp/ipykernel_34276/915070416.py:69: RuntimeWarning: invalid value encountered in subtract
  self.weights -= self.learning_rate * dw_single
100%|███████████████████████████████████████| 1000/1000 [03:44<00:00,  4.45it/s]

Тренировочные данные: MAE=nan, RMSE=nan, R²=1.0000
Тестовые данные:     MAE=nan, RMSE=nan, R²=1.0000

In [123]:
my_minmax_scaler = MyMinMaxScaler()
my_std_scaler = MyStandardScaler()
sklearn_minmax_scaler = MinMaxScaler()
sklearn_std_scaler = StandardScaler()

X_train_my_minmax = my_minmax_scaler.fit_transform(X_train)
X_test_my_minmax = my_minmax_scaler.transform(X_test)
X_train_my_std = my_std_scaler.fit_transform(X_train)
X_test_my_std = my_std_scaler.transform(X_test)

X_train_sklearn_minmax = sklearn_minmax_scaler.fit_transform(X_train)
X_test_sklearn_minmax = sklearn_minmax_scaler.transform(X_test)
X_train_sklearn_std = sklearn_std_scaler.fit_transform(X_train)
X_test_sklearn_std = sklearn_std_scaler.transform(X_test)

models = {
    "My Batch GD (L1)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0.01, lambda2=0),
    "My Batch GD (L2)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0, lambda2=0.01),
    "My Batch GD (L1+L2)": LinearRegression_my(method='Batch_Gradient_Descent', lambda1=0.01, lambda2=0.01),
    
    "My Stochastic GD (L1)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0.01, lambda2=0),
    "My Stochastic GD (L2)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0, lambda2=0.01),
    "My Stochastic GD (L1+L2)": LinearRegression_my(method='Stochastic_Gradient_Descent', lambda1=0.01, lambda2=0.01),
    
    "Sklearn Lasso": Lasso(alpha=0.01, random_state=42),
    "Sklearn Ridge": Ridge(alpha=0.01, random_state=42),
    "Sklearn ElasticNet": ElasticNet(alpha=0.01, l1_ratio=0.5, random_state=42)
}

print("Сравнение различных реализаций линейной регрессии:")
print("=" * 70)

for scaler in [0, 1]:  
    for name, model in models.items():
        current_name = name 
        if scaler:
            current_name += " norm = std"  
        else:
            current_name += " norm = minmax"
            
        print(f"\n=== {current_name} ===")
        
        if "My" in name:
            # Свои модели на своих нормализаторах
            if scaler:  # std
                X_train_curr = X_train_my_std  
                X_test_curr = X_test_my_std
            else:  # minmax
                X_train_curr = X_train_my_minmax
                X_test_curr = X_test_my_minmax
        else:
            # Sklearn модели на sklearn нормализаторах  
            if scaler:  # std
                X_train_curr = X_train_sklearn_std  
                X_test_curr = X_test_sklearn_std
            else:  # minmax
                X_train_curr = X_train_sklearn_minmax
                X_test_curr = X_test_sklearn_minmax
        
        model.fit(X_train_curr, y_train)
        
        if "Sklearn" in name:
            y_pred_train = model.predict(X_train_curr)
            y_pred_test = model.predict(X_test_curr)
            
            mae_train = mean_absolute_error(y_train, y_pred_train)
            rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
            r2_train = r2_score(y_train, y_pred_train)
            
            mae_test = mean_absolute_error(y_test, y_pred_test)
            rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
            r2_test = r2_score(y_test, y_pred_test)
            
        else:
            mae_train = model.mae(X_train_curr, y_train)
            rmse_train = model.rmse(X_train_curr, y_train)
            r2_train = model.r2_score(X_train_curr, y_train)
            
            mae_test = model.mae(X_test_curr, y_test)
            rmse_test = model.rmse(X_test_curr, y_test)
            r2_test = model.r2_score(X_test_curr, y_test)
        
        print(f"Тренировочные данные: MAE={mae_train:.4f}, RMSE={rmse_train:.4f}, R²={r2_train:.4f}")
        print(f"Тестовые данные:     MAE={mae_test:.4f}, RMSE={rmse_test:.4f}, R²={r2_test:.4f}")
        
        result_MAE_2, result_RMSE_2, result_R2_2 = push_metrics(current_name, model, X_train_curr, y_train, X_test_curr, y_test, 
                result_MAE=result_MAE_2, result_RMSE=result_RMSE_2, result_R2=result_R2_2)

Сравнение различных реализаций линейной регрессии:
======================================================================

=== My Batch GD (L1) norm = minmax ===

100%|██████████████████████████████████████| 1000/1000 [00:06<00:00, 146.75it/s]

Тренировочные данные: MAE=925.5146, RMSE=1322.3348, R²=0.3045
Тестовые данные:     MAE=364625.4899, RMSE=98386164.3051, R²=-3909255942.0265

=== My Batch GD (L2) norm = minmax ===

100%|██████████████████████████████████████| 1000/1000 [00:06<00:00, 146.54it/s]

Тренировочные данные: MAE=932.9129, RMSE=1331.7888, R²=0.2945
Тестовые данные:     MAE=369394.7540, RMSE=99674373.5873, R²=-4012297027.3723

=== My Batch GD (L1+L2) norm = minmax ===

100%|██████████████████████████████████████| 1000/1000 [00:06<00:00, 145.80it/s]

Тренировочные данные: MAE=932.9251, RMSE=1331.8051, R²=0.2945
Тестовые данные:     MAE=337541.6126, RMSE=91057580.6920, R²=-3348561354.5485

=== My Stochastic GD (L1) norm = minmax ===

100%|███████████████████████████████████████| 1000/1000 [04:56<00:00,  3.38it/s]

Тренировочные данные: MAE=762.2984, RMSE=1107.0232, R²=0.5126
Тестовые данные:     MAE=31826029.1348, RMSE=8609238526.2866, R²=-29933364018607.8047

=== My Stochastic GD (L2) norm = minmax ===

100%|███████████████████████████████████████| 1000/1000 [04:32<00:00,  3.67it/s]

Тренировочные данные: MAE=814.5476, RMSE=1232.8799, R²=0.3954
Тестовые данные:     MAE=1656306.0042, RMSE=447836641.3261, R²=-80996321250.7580

=== My Stochastic GD (L1+L2) norm = minmax ===

100%|███████████████████████████████████████| 1000/1000 [05:47<00:00,  2.88it/s]

Тренировочные данные: MAE=814.5622, RMSE=1232.9096, R²=0.3954
Тестовые данные:     MAE=1121246.0865, RMSE=303094280.8260, R²=-37100650933.2695

=== Sklearn Lasso norm = minmax ===

/home/renat/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.113e+10, tolerance: 1.215e+07
  model = cd_fast.enet_coordinate_descent(

Тренировочные данные: MAE=760.6943, RMSE=1084.9399, R²=0.5318
Тестовые данные:     MAE=506663486.2042, RMSE=137060449767.7053, R²=-7586655284757626.0000

=== Sklearn Ridge norm = minmax ===
Тренировочные данные: MAE=759.9875, RMSE=1082.8689, R²=0.5336
Тестовые данные:     MAE=6068495173.3764, RMSE=1641625603898.0378, R²=-1088364281027107072.0000

=== Sklearn ElasticNet norm = minmax ===
Тренировочные данные: MAE=823.3424, RMSE=1191.2146, R²=0.4356
Тестовые данные:     MAE=19246644.9005, RMSE=5206304407.0818, R²=-10946749012811.7520

=== My Batch GD (L1) norm = std ===

100%|██████████████████████████████████████| 1000/1000 [00:06<00:00, 146.80it/s]

Тренировочные данные: MAE=769.2836, RMSE=1096.0711, R²=0.5222
Тестовые данные:     MAE=1506008564.6034, RMSE=407399357238.6356, R²=-67029615030175104.0000

=== My Batch GD (L2) norm = std ===

100%|██████████████████████████████████████| 1000/1000 [00:07<00:00, 126.67it/s]

Тренировочные данные: MAE=769.5052, RMSE=1096.3461, R²=0.5219
Тестовые данные:     MAE=1523051475.0950, RMSE=412009739990.9006, R²=-68555296281358120.0000

=== My Batch GD (L1+L2) norm = std ===

100%|██████████████████████████████████████| 1000/1000 [00:07<00:00, 139.50it/s]

Тренировочные данные: MAE=769.5074, RMSE=1096.3485, R²=0.5219
Тестовые данные:     MAE=1522054819.2378, RMSE=411740128527.9835, R²=-68465603032063592.0000

=== My Stochastic GD (L1) norm = std ===

  0%|                                          | 1/1000 [00:00<05:10,  3.22it/s]/tmp/ipykernel_34276/915070416.py:61: RuntimeWarning: overflow encountered in multiply
  dw_single = 2 * xi * (y_pred - yi)
/tmp/ipykernel_34276/915070416.py:69: RuntimeWarning: invalid value encountered in subtract
  self.weights -= self.learning_rate * dw_single
100%|███████████████████████████████████████| 1000/1000 [04:59<00:00,  3.34it/s]

Тренировочные данные: MAE=nan, RMSE=nan, R²=1.0000
Тестовые данные:     MAE=nan, RMSE=nan, R²=1.0000

=== My Stochastic GD (L2) norm = std ===

  0%|                                          | 1/1000 [00:00<04:34,  3.64it/s]/tmp/ipykernel_34276/915070416.py:61: RuntimeWarning: overflow encountered in multiply
  dw_single = 2 * xi * (y_pred - yi)
/tmp/ipykernel_34276/915070416.py:59: RuntimeWarning: invalid value encountered in matmul
  y_pred = xi @ self.weights + self.bias
100%|███████████████████████████████████████| 1000/1000 [04:40<00:00,  3.56it/s]

Тренировочные данные: MAE=nan, RMSE=nan, R²=1.0000
Тестовые данные:     MAE=nan, RMSE=nan, R²=1.0000

=== My Stochastic GD (L1+L2) norm = std ===

  0%|                                          | 1/1000 [00:00<05:46,  2.89it/s]/tmp/ipykernel_34276/915070416.py:61: RuntimeWarning: overflow encountered in multiply
  dw_single = 2 * xi * (y_pred - yi)
/tmp/ipykernel_34276/915070416.py:59: RuntimeWarning: invalid value encountered in matmul
  y_pred = xi @ self.weights + self.bias
100%|███████████████████████████████████████| 1000/1000 [05:52<00:00,  2.84it/s]

Тренировочные данные: MAE=nan, RMSE=nan, R²=1.0000
Тестовые данные:     MAE=nan, RMSE=nan, R²=1.0000

=== Sklearn Lasso norm = std ===

/home/renat/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.706e+10, tolerance: 1.215e+07
  model = cd_fast.enet_coordinate_descent(

Тренировочные данные: MAE=759.5028, RMSE=1080.5278, R²=0.5356
Тестовые данные:     MAE=7498001090.6682, RMSE=2028329654819.2424, R²=-1661510639506571008.0000

=== Sklearn Ridge norm = std ===
Тренировочные данные: MAE=755.0464, RMSE=1073.1343, R²=0.5419
Тестовые данные:     MAE=80775491504.1848, RMSE=21851070952080.0586, R²=-192828623302265929728.0000

=== Sklearn ElasticNet norm = std ===
Тренировочные данные: MAE=763.6262, RMSE=1088.3081, R²=0.5289
Тестовые данные:     MAE=11070788083.1850, RMSE=2994826585611.0791, R²=-3622174807955181056.0000

/home/renat/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.809e+10, tolerance: 1.215e+07
  model = cd_fast.enet_coordinate_descent(

In [124]:

print("СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ:")
print("="*70)

print("\nМетрика MAE:")
print(result_MAE_2.round(4))

print("\nМетрика RMSE:")
print(result_RMSE_2.round(4))

print("\nМетрика R²:")
print(result_R2.round(4))

СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ:
======================================================================

Метрика MAE:
                                     model         train          test metric
0    Sklearn LinearRegression (Analytical)  7.536761e+02  2.779448e+18    MAE
1     Sklearn SGDRegressor (Deterministic)  4.591350e+22  5.134517e+31    MAE
2    My LinearRegression (Normal Equation)  1.185417e+03  1.057450e+14    MAE
3           My LinearRegression (Batch GD)           NaN           NaN    MAE
4      My LinearRegression (Stochastic GD)           NaN           NaN    MAE
5           My Batch GD (L1) norm = minmax  9.255146e+02  3.646255e+05    MAE
6           My Batch GD (L2) norm = minmax  9.329129e+02  3.693948e+05    MAE
7        My Batch GD (L1+L2) norm = minmax  9.329251e+02  3.375416e+05    MAE
8      My Stochastic GD (L1) norm = minmax  7.622984e+02  3.182603e+07    MAE
9      My Stochastic GD (L2) norm = minmax  8.145476e+02  1.656306e+06    MAE
10  My Stochastic GD (L1+L2) norm = minmax  8.145622e+02  1.121246e+06    MAE
11             Sklearn Lasso norm = minmax  7.606943e+02  5.066635e+08    MAE
12             Sklearn Ridge norm = minmax  7.599875e+02  6.068495e+09    MAE
13        Sklearn ElasticNet norm = minmax  8.233424e+02  1.924664e+07    MAE
14             My Batch GD (L1) norm = std  7.692836e+02  1.506009e+09    MAE
15             My Batch GD (L2) norm = std  7.695052e+02  1.523051e+09    MAE
16          My Batch GD (L1+L2) norm = std  7.695074e+02  1.522055e+09    MAE
17        My Stochastic GD (L1) norm = std           NaN           NaN    MAE
18        My Stochastic GD (L2) norm = std           NaN           NaN    MAE
19     My Stochastic GD (L1+L2) norm = std           NaN           NaN    MAE
20                Sklearn Lasso norm = std  7.595028e+02  7.498001e+09    MAE
21                Sklearn Ridge norm = std  7.550464e+02  8.077549e+10    MAE
22           Sklearn ElasticNet norm = std  7.636262e+02  1.107079e+10    MAE

Метрика RMSE:
                                     model         train          test metric
0    Sklearn LinearRegression (Analytical)  1.070599e+03  7.518857e+20   RMSE
1     Sklearn SGDRegressor (Deterministic)  1.850982e+24  1.388970e+34   RMSE
2    My LinearRegression (Normal Equation)  1.512623e+03  2.860572e+16   RMSE
3           My LinearRegression (Batch GD)           NaN           NaN   RMSE
4      My LinearRegression (Stochastic GD)           NaN           NaN   RMSE
5           My Batch GD (L1) norm = minmax  1.322335e+03  9.838616e+07   RMSE
6           My Batch GD (L2) norm = minmax  1.331789e+03  9.967437e+07   RMSE
7        My Batch GD (L1+L2) norm = minmax  1.331805e+03  9.105758e+07   RMSE
8      My Stochastic GD (L1) norm = minmax  1.107023e+03  8.609239e+09   RMSE
9      My Stochastic GD (L2) norm = minmax  1.232880e+03  4.478366e+08   RMSE
10  My Stochastic GD (L1+L2) norm = minmax  1.232910e+03  3.030943e+08   RMSE
11             Sklearn Lasso norm = minmax  1.084940e+03  1.370604e+11   RMSE
12             Sklearn Ridge norm = minmax  1.082869e+03  1.641626e+12   RMSE
13        Sklearn ElasticNet norm = minmax  1.191215e+03  5.206304e+09   RMSE
14             My Batch GD (L1) norm = std  1.096071e+03  4.073994e+11   RMSE
15             My Batch GD (L2) norm = std  1.096346e+03  4.120097e+11   RMSE
16          My Batch GD (L1+L2) norm = std  1.096349e+03  4.117401e+11   RMSE
17        My Stochastic GD (L1) norm = std           NaN           NaN   RMSE
18        My Stochastic GD (L2) norm = std           NaN           NaN   RMSE
19     My Stochastic GD (L1+L2) norm = std           NaN           NaN   RMSE
20                Sklearn Lasso norm = std  1.080528e+03  2.028330e+12   RMSE
21                Sklearn Ridge norm = std  1.073134e+03  2.185107e+13   RMSE
22           Sklearn ElasticNet norm = std  1.088308e+03  2.994827e+12   RMSE

Метрика R²:
                                     model   train    test metric
0    Sklearn LinearRegression (Analytical)  0.5803  0.4052     R2
1     Sklearn SGDRegressor (Deterministic)  0.5801  0.4067     R2
2    My LinearRegression (Normal Equation)  0.5803  0.4052     R2
3           My LinearRegression (Batch GD)  0.5791  0.4138     R2
4      My LinearRegression (Stochastic GD)  0.3594  0.2277     R2
5                         My Batch GD (L1)  0.5791  0.4138     R2
6                         My Batch GD (L2)  0.5786  0.4203     R2
7                      My Batch GD (L1+L2)  0.5786  0.4203     R2
8                    My Stochastic GD (L1)  0.3593  0.2277     R2
9                    My Stochastic GD (L2)  0.3565  0.2336     R2
10                My Stochastic GD (L1+L2)  0.3565  0.2336     R2
11                           Sklearn Lasso  0.5803  0.4052     R2
12                           Sklearn Ridge  0.5803  0.4052     R2
13                      Sklearn ElasticNet  0.5800  0.4145     R2
14          My Batch GD (L1) norm = minmax  0.3499  0.3488     R2
15          My Batch GD (L2) norm = minmax  0.3421  0.3413     R2
16       My Batch GD (L1+L2) norm = minmax  0.3421  0.3413     R2
17     My Stochastic GD (L1) norm = minmax  0.5238  0.3525     R2
18     My Stochastic GD (L2) norm = minmax  0.4367  0.4246     R2
19  My Stochastic GD (L1+L2) norm = minmax  0.4367  0.4246     R2
20             Sklearn Lasso norm = minmax  0.5803  0.4053     R2
21             Sklearn Ridge norm = minmax  0.5803  0.4052     R2
22        Sklearn ElasticNet norm = minmax  0.4941  0.4801     R2
23             My Batch GD (L1) norm = std  0.5803  0.4052     R2
24             My Batch GD (L2) norm = std  0.5802  0.4066     R2
25          My Batch GD (L1+L2) norm = std  0.5802  0.4066     R2
26        My Stochastic GD (L1) norm = std  0.4966  0.3759     R2
27        My Stochastic GD (L2) norm = std  0.4967  0.3770     R2
28     My Stochastic GD (L1+L2) norm = std  0.4967  0.3770     R2
29                Sklearn Lasso norm = std  0.5803  0.4052     R2
30                Sklearn Ridge norm = std  0.5803  0.4052     R2
31           Sklearn ElasticNet norm = std  0.5803  0.4066     R2

## 9. Нативные модели
### Рассчитайте средние и медианные показатели из предыдущего урока и добавьте результаты в итоговый фрейм данных.

In [126]:
X_full = pd.concat([X_train, X_test])
y_full = pd.concat([y_train, y_test])

dummy_configs = [
    ("naive_mean", "mean", X_train, y_train, X_test, y_test),
    ("naive_median", "median", X_train, y_train, X_test, y_test),
    ("naive_mean_full", "mean", X_full, y_full, X_test, y_test),
    ("naive_median_full", "median", X_full, y_full, X_test, y_test),
    ("naive_mean_full_train", "mean", X_full, y_full, X_train, y_train),
    ("naive_median_full_train", "median", X_full, y_full, X_train, y_train)
]

for name, strategy, X_tr, y_tr, X_te, y_te in dummy_configs:
    model = DummyRegressor(strategy=strategy)
    model.fit(X_tr, y_tr)
    
    y_pred_train = model.predict(X_tr)
    y_pred_test = model.predict(X_te)
    
    mae_train = mean_absolute_error(y_tr, y_pred_train)
    mae_test = mean_absolute_error(y_te, y_pred_test)
    
    rmse_train = np.sqrt(mean_squared_error(y_tr, y_pred_train))
    rmse_test = np.sqrt(mean_squared_error(y_te, y_pred_test))
    
    r2_train = r2_score(y_tr, y_pred_train)
    r2_test = r2_score(y_te, y_pred_test)
    
    next_index_MAE = len(result_MAE_2)
    next_index_RMSE = len(result_RMSE_2)
    next_index_R2 = len(result_R2_2)
    
    result_MAE_2.loc[next_index_MAE] = [name, mae_train, mae_test, "MAE"]
    result_RMSE_2.loc[next_index_RMSE] = [name, rmse_train, rmse_test, "RMSE"]
    result_R2_2.loc[next_index_R2] = [name, r2_train, r2_test, "R2"]

## 10. Сравнить результаты

In [128]:
print("СВОДНАЯ ТАБЛИЦА 1 РЕЗУЛЬТАТОВ:")
print("="*70)

print("\nМетрика MAE:")
print(result_MAE.round(4))

print("\nМетрика RMSE:")
print(result_RMSE.round(4))

print("\nМетрика R²:")
print(result_R2.round(4))

СВОДНАЯ ТАБЛИЦА 1 РЕЗУЛЬТАТОВ:
======================================================================

Метрика MAE:
                                     model     train      test metric
0    Sklearn LinearRegression (Analytical)  708.7371  713.0153    MAE
1     Sklearn SGDRegressor (Deterministic)  707.1975  711.4176    MAE
2    My LinearRegression (Normal Equation)  708.7371  713.0153    MAE
3           My LinearRegression (Batch GD)  708.9878  713.1200    MAE
4      My LinearRegression (Stochastic GD)  863.7366  865.0665    MAE
5                         My Batch GD (L1)  708.9874  713.1195    MAE
6                         My Batch GD (L2)  708.8934  712.9005    MAE
7                      My Batch GD (L1+L2)  708.8934  712.9004    MAE
8                    My Stochastic GD (L1)  863.7421  865.0710    MAE
9                    My Stochastic GD (L2)  862.1839  863.2878    MAE
10                My Stochastic GD (L1+L2)  862.1910  863.2942    MAE
11                           Sklearn Lasso  708.7313  713.0093    MAE
12                           Sklearn Ridge  708.7371  713.0153    MAE
13                      Sklearn ElasticNet  708.2902  712.3643    MAE
14          My Batch GD (L1) norm = minmax  885.3194  884.0764    MAE
15          My Batch GD (L2) norm = minmax  891.2906  889.9334    MAE
16       My Batch GD (L1+L2) norm = minmax  891.2964  889.9392    MAE
17     My Stochastic GD (L1) norm = minmax  742.4449  745.7200    MAE
18     My Stochastic GD (L2) norm = minmax  773.3136  774.3773    MAE
19  My Stochastic GD (L1+L2) norm = minmax  773.3174  774.3809    MAE
20             Sklearn Lasso norm = minmax  708.7330  713.0088    MAE
21             Sklearn Ridge norm = minmax  708.7377  713.0152    MAE
22        Sklearn ElasticNet norm = minmax  768.8756  769.8145    MAE
23             My Batch GD (L1) norm = std  708.7641  713.0482    MAE
24             My Batch GD (L2) norm = std  708.6524  712.8974    MAE
25          My Batch GD (L1+L2) norm = std  708.6516  712.8965    MAE
26        My Stochastic GD (L1) norm = std  785.6379  788.4443    MAE
27        My Stochastic GD (L2) norm = std  784.9306  787.7481    MAE
28     My Stochastic GD (L1+L2) norm = std  784.9258  787.7435    MAE
29                Sklearn Lasso norm = std  708.7350  713.0132    MAE
30                Sklearn Ridge norm = std  708.7371  713.0153    MAE
31           Sklearn ElasticNet norm = std  708.6224  712.8605    MAE

Метрика RMSE:
                                     model      train       test metric
0    Sklearn LinearRegression (Analytical)  1027.2629  1213.5977   RMSE
1     Sklearn SGDRegressor (Deterministic)  1027.4142  1212.1024   RMSE
2    My LinearRegression (Normal Equation)  1027.2629  1213.5977   RMSE
3           My LinearRegression (Batch GD)  1028.6358  1204.7987   RMSE
4      My LinearRegression (Stochastic GD)  1269.1302  1382.8212   RMSE
5                         My Batch GD (L1)  1028.6374  1204.7978   RMSE
6                         My Batch GD (L2)  1029.2567  1198.0668   RMSE
7                      My Batch GD (L1+L2)  1029.2586  1198.0662   RMSE
8                    My Stochastic GD (L1)  1269.1439  1382.8301   RMSE
9                    My Stochastic GD (L2)  1271.9539  1377.5579   RMSE
10                My Stochastic GD (L1+L2)  1271.9699  1377.5693   RMSE
11                           Sklearn Lasso  1027.2629  1213.5945   RMSE
12                           Sklearn Ridge  1027.2629  1213.5973   RMSE
13                      Sklearn ElasticNet  1027.5323  1204.0805   RMSE
14          My Batch GD (L1) norm = minmax  1278.4919  1269.7893   RMSE
15          My Batch GD (L2) norm = minmax  1286.1148  1277.1397   RMSE
16       My Batch GD (L1+L2) norm = minmax  1286.1221  1277.1468   RMSE
17     My Stochastic GD (L1) norm = minmax  1094.1328  1266.2137   RMSE
18     My Stochastic GD (L2) norm = minmax  1190.0275  1193.6149   RMSE
19  My Stochastic GD (L1+L2) norm = minmax  1190.0497  1193.6328   RMSE
20             Sklearn Lasso norm = minmax  1027.2629  1213.4736   RMSE
21             Sklearn Ridge norm = minmax  1027.2629  1213.5483   RMSE
22        Sklearn ElasticNet norm = minmax  1127.7674  1134.5994   RMSE
23             My Batch GD (L1) norm = std  1027.2784  1213.6027   RMSE
24             My Batch GD (L2) norm = std  1027.2912  1212.2130   RMSE
25          My Batch GD (L1+L2) norm = std  1027.2913  1212.2131   RMSE
26        My Stochastic GD (L1) norm = std  1124.9997  1243.1291   RMSE
27        My Stochastic GD (L2) norm = std  1124.8753  1242.0094   RMSE
28     My Stochastic GD (L1+L2) norm = std  1124.8717  1242.0068   RMSE
29                Sklearn Lasso norm = std  1027.2629  1213.5976   RMSE
30                Sklearn Ridge norm = std  1027.2629  1213.5976   RMSE
31           Sklearn ElasticNet norm = std  1027.2737  1212.2041   RMSE

Метрика R²:
                                     model   train    test metric
0    Sklearn LinearRegression (Analytical)  0.5803  0.4052     R2
1     Sklearn SGDRegressor (Deterministic)  0.5801  0.4067     R2
2    My LinearRegression (Normal Equation)  0.5803  0.4052     R2
3           My LinearRegression (Batch GD)  0.5791  0.4138     R2
4      My LinearRegression (Stochastic GD)  0.3594  0.2277     R2
5                         My Batch GD (L1)  0.5791  0.4138     R2
6                         My Batch GD (L2)  0.5786  0.4203     R2
7                      My Batch GD (L1+L2)  0.5786  0.4203     R2
8                    My Stochastic GD (L1)  0.3593  0.2277     R2
9                    My Stochastic GD (L2)  0.3565  0.2336     R2
10                My Stochastic GD (L1+L2)  0.3565  0.2336     R2
11                           Sklearn Lasso  0.5803  0.4052     R2
12                           Sklearn Ridge  0.5803  0.4052     R2
13                      Sklearn ElasticNet  0.5800  0.4145     R2
14          My Batch GD (L1) norm = minmax  0.3499  0.3488     R2
15          My Batch GD (L2) norm = minmax  0.3421  0.3413     R2
16       My Batch GD (L1+L2) norm = minmax  0.3421  0.3413     R2
17     My Stochastic GD (L1) norm = minmax  0.5238  0.3525     R2
18     My Stochastic GD (L2) norm = minmax  0.4367  0.4246     R2
19  My Stochastic GD (L1+L2) norm = minmax  0.4367  0.4246     R2
20             Sklearn Lasso norm = minmax  0.5803  0.4053     R2
21             Sklearn Ridge norm = minmax  0.5803  0.4052     R2
22        Sklearn ElasticNet norm = minmax  0.4941  0.4801     R2
23             My Batch GD (L1) norm = std  0.5803  0.4052     R2
24             My Batch GD (L2) norm = std  0.5802  0.4066     R2
25          My Batch GD (L1+L2) norm = std  0.5802  0.4066     R2
26        My Stochastic GD (L1) norm = std  0.4966  0.3759     R2
27        My Stochastic GD (L2) norm = std  0.4967  0.3770     R2
28     My Stochastic GD (L1+L2) norm = std  0.4967  0.3770     R2
29                Sklearn Lasso norm = std  0.5803  0.4052     R2
30                Sklearn Ridge norm = std  0.5803  0.4052     R2
31           Sklearn ElasticNet norm = std  0.5803  0.4066     R2

In [129]:
print("СВОДНАЯ ТАБЛИЦА 2 РЕЗУЛЬТАТОВ:")
print("="*70)

print("\nМетрика MAE:")
print(result_MAE_2.round(4))

print("\nМетрика RMSE:")
print(result_RMSE_2.round(4))

print("\nМетрика R²:")
print(result_R2_2.round(4))

СВОДНАЯ ТАБЛИЦА 2 РЕЗУЛЬТАТОВ:
======================================================================

Метрика MAE:
                                     model         train          test metric
0    Sklearn LinearRegression (Analytical)  7.536761e+02  2.779448e+18    MAE
1     Sklearn SGDRegressor (Deterministic)  4.591350e+22  5.134517e+31    MAE
2    My LinearRegression (Normal Equation)  1.185417e+03  1.057450e+14    MAE
3           My LinearRegression (Batch GD)           NaN           NaN    MAE
4      My LinearRegression (Stochastic GD)           NaN           NaN    MAE
5           My Batch GD (L1) norm = minmax  9.255146e+02  3.646255e+05    MAE
6           My Batch GD (L2) norm = minmax  9.329129e+02  3.693948e+05    MAE
7        My Batch GD (L1+L2) norm = minmax  9.329251e+02  3.375416e+05    MAE
8      My Stochastic GD (L1) norm = minmax  7.622984e+02  3.182603e+07    MAE
9      My Stochastic GD (L2) norm = minmax  8.145476e+02  1.656306e+06    MAE
10  My Stochastic GD (L1+L2) norm = minmax  8.145622e+02  1.121246e+06    MAE
11             Sklearn Lasso norm = minmax  7.606943e+02  5.066635e+08    MAE
12             Sklearn Ridge norm = minmax  7.599875e+02  6.068495e+09    MAE
13        Sklearn ElasticNet norm = minmax  8.233424e+02  1.924664e+07    MAE
14             My Batch GD (L1) norm = std  7.692836e+02  1.506009e+09    MAE
15             My Batch GD (L2) norm = std  7.695052e+02  1.523051e+09    MAE
16          My Batch GD (L1+L2) norm = std  7.695074e+02  1.522055e+09    MAE
17        My Stochastic GD (L1) norm = std           NaN           NaN    MAE
18        My Stochastic GD (L2) norm = std           NaN           NaN    MAE
19     My Stochastic GD (L1+L2) norm = std           NaN           NaN    MAE
20                Sklearn Lasso norm = std  7.595028e+02  7.498001e+09    MAE
21                Sklearn Ridge norm = std  7.550464e+02  8.077549e+10    MAE
22           Sklearn ElasticNet norm = std  7.636262e+02  1.107079e+10    MAE
23                              naive_mean  1.134361e+03  1.131498e+03    MAE
24                            naive_median  1.082221e+03  1.079060e+03    MAE
25                         naive_mean_full  1.131213e+03  1.130077e+03    MAE
26                       naive_median_full  1.080317e+03  1.079060e+03    MAE
27                   naive_mean_full_train  1.131213e+03  1.132934e+03    MAE
28                 naive_median_full_train  1.080317e+03  1.082221e+03    MAE

Метрика RMSE:
                                     model         train          test metric
0    Sklearn LinearRegression (Analytical)  1.070599e+03  7.518857e+20   RMSE
1     Sklearn SGDRegressor (Deterministic)  1.850982e+24  1.388970e+34   RMSE
2    My LinearRegression (Normal Equation)  1.512623e+03  2.860572e+16   RMSE
3           My LinearRegression (Batch GD)           NaN           NaN   RMSE
4      My LinearRegression (Stochastic GD)           NaN           NaN   RMSE
5           My Batch GD (L1) norm = minmax  1.322335e+03  9.838616e+07   RMSE
6           My Batch GD (L2) norm = minmax  1.331789e+03  9.967437e+07   RMSE
7        My Batch GD (L1+L2) norm = minmax  1.331805e+03  9.105758e+07   RMSE
8      My Stochastic GD (L1) norm = minmax  1.107023e+03  8.609239e+09   RMSE
9      My Stochastic GD (L2) norm = minmax  1.232880e+03  4.478366e+08   RMSE
10  My Stochastic GD (L1+L2) norm = minmax  1.232910e+03  3.030943e+08   RMSE
11             Sklearn Lasso norm = minmax  1.084940e+03  1.370604e+11   RMSE
12             Sklearn Ridge norm = minmax  1.082869e+03  1.641626e+12   RMSE
13        Sklearn ElasticNet norm = minmax  1.191215e+03  5.206304e+09   RMSE
14             My Batch GD (L1) norm = std  1.096071e+03  4.073994e+11   RMSE
15             My Batch GD (L2) norm = std  1.096346e+03  4.120097e+11   RMSE
16          My Batch GD (L1+L2) norm = std  1.096349e+03  4.117401e+11   RMSE
17        My Stochastic GD (L1) norm = std           NaN           NaN   RMSE
18        My Stochastic GD (L2) norm = std           NaN           NaN   RMSE
19     My Stochastic GD (L1+L2) norm = std           NaN           NaN   RMSE
20                Sklearn Lasso norm = std  1.080528e+03  2.028330e+12   RMSE
21                Sklearn Ridge norm = std  1.073134e+03  2.185107e+13   RMSE
22           Sklearn ElasticNet norm = std  1.088308e+03  2.994827e+12   RMSE
23                              naive_mean  1.585609e+03  1.573598e+03   RMSE
24                            naive_median  1.631720e+03  1.617942e+03   RMSE
25                         naive_mean_full  1.578378e+03  1.573577e+03   RMSE
26                       naive_median_full  1.623437e+03  1.617942e+03   RMSE
27                   naive_mean_full_train  1.578378e+03  1.585618e+03   RMSE
28                 naive_median_full_train  1.623437e+03  1.631720e+03   RMSE

Метрика R²:
                                     model         train          test metric
0    Sklearn LinearRegression (Analytical)  5.441000e-01 -2.283125e+35     R2
1     Sklearn SGDRegressor (Deterministic) -1.362737e+42 -7.791329e+61     R2
2    My LinearRegression (Normal Equation)  8.990000e-02 -3.304698e+26     R2
3           My LinearRegression (Batch GD)  1.000000e+00  1.000000e+00     R2
4      My LinearRegression (Stochastic GD)  1.000000e+00  1.000000e+00     R2
5           My Batch GD (L1) norm = minmax  3.045000e-01 -3.909256e+09     R2
6           My Batch GD (L2) norm = minmax  2.945000e-01 -4.012297e+09     R2
7        My Batch GD (L1+L2) norm = minmax  2.945000e-01 -3.348561e+09     R2
8      My Stochastic GD (L1) norm = minmax  5.126000e-01 -2.993336e+13     R2
9      My Stochastic GD (L2) norm = minmax  3.954000e-01 -8.099632e+10     R2
10  My Stochastic GD (L1+L2) norm = minmax  3.954000e-01 -3.710065e+10     R2
11             Sklearn Lasso norm = minmax  5.318000e-01 -7.586655e+15     R2
12             Sklearn Ridge norm = minmax  5.336000e-01 -1.088364e+18     R2
13        Sklearn ElasticNet norm = minmax  4.356000e-01 -1.094675e+13     R2
14             My Batch GD (L1) norm = std  5.222000e-01 -6.702962e+16     R2
15             My Batch GD (L2) norm = std  5.219000e-01 -6.855530e+16     R2
16          My Batch GD (L1+L2) norm = std  5.219000e-01 -6.846560e+16     R2
17        My Stochastic GD (L1) norm = std  1.000000e+00  1.000000e+00     R2
18        My Stochastic GD (L2) norm = std  1.000000e+00  1.000000e+00     R2
19     My Stochastic GD (L1+L2) norm = std  1.000000e+00  1.000000e+00     R2
20                Sklearn Lasso norm = std  5.356000e-01 -1.661511e+18     R2
21                Sklearn Ridge norm = std  5.419000e-01 -1.928286e+20     R2
22           Sklearn ElasticNet norm = std  5.289000e-01 -3.622175e+18     R2
23                              naive_mean  0.000000e+00 -0.000000e+00     R2
24                            naive_median -5.900000e-02 -5.720000e-02     R2
25                         naive_mean_full  0.000000e+00 -0.000000e+00     R2
26                       naive_median_full -5.790000e-02 -5.720000e-02     R2
27                   naive_mean_full_train  0.000000e+00 -0.000000e+00     R2
28                 naive_median_full_train -5.790000e-02 -5.900000e-02     R2

### Какая модель лучшая?

My Batch GD (L1) - Lasso\
   • Test MAE: 713.1195 | Test R²: 0.4138\
   • Стабильность: разница train/test = 0.58%

## 11. Задача на сложение

In [192]:
# БЛОК 1: Логарифмическое преобразование целевой переменной
print("="*50)
print("1. ЛОГАРИФМИЧЕСКОЕ ПРЕОБРАЗОВАНИЕ")
print("="*50)

# Создаем копии данных для преобразования
X_train_log = X_train.copy()
X_test_log = X_test.copy()
y_train_log = y_train.copy()
y_test_log = y_test.copy()

# Применяем логарифмирование к целевой переменной
y_train_log = np.log1p(y_train_log)

# Нормализуем признаки
my_minmax_scaler_log = MyMinMaxScaler()
X_train_log_scaled = my_minmax_scaler_log.fit_transform(X_train_log)
X_test_log_scaled = my_minmax_scaler_log.transform(X_test_log)

# Обучаем модель с очень маленькой скоростью обучения и сильной регуляризацией
model_lasso_log = LinearRegression_my(method='Batch_Gradient_Descent', 
                                     lambda1=0.01, lambda2=0, 
                                     learning_rate=0.01)
model_lasso_log.fit(X_train_log_scaled, y_train_log, epochs=1000)

# Предсказания на тренировочных данных
y_train_pred_log = model_lasso_log.predict(X_train_log_scaled)
y_train_pred_log_clipped = np.clip(y_train_pred_log, np.log1p(quanil_1), np.log1p(quanil_99))
y_train_pred = np.expm1(y_train_pred_log_clipped)

# Предсказания на тестовых данных
y_test_pred_log = model_lasso_log.predict(X_test_log_scaled)
y_test_pred_log_clipped = np.clip(y_test_pred_log, np.log1p(quanil_1), np.log1p(quanil_99))
y_test_pred = np.expm1(y_test_pred_log_clipped)

# Метрики для тренировочных данных
mae_train = mean_absolute_error(y_train, y_train_pred)
rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
r2_train = r2_score(y_train, y_train_pred)

# Метрики для тестовых данных
mae_test = mean_absolute_error(y_test, y_test_pred)
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_test = r2_score(y_test, y_test_pred)

print(f"My Lasso (Batch GD) with log transform:")
print(f"Тренировочные данные: MAE={mae_train:.4f}, RMSE={rmse_train:.4f}, R²={r2_train:.4f}")
print(f"Тестовые данные:     MAE={mae_test:.4f}, RMSE={rmse_test:.4f}, R²={r2_test:.4f}")

==================================================
1. ЛОГАРИФМИЧЕСКОЕ ПРЕОБРАЗОВАНИЕ
==================================================

100%|██████████████████████████████████████| 1000/1000 [00:05<00:00, 195.51it/s]

My Lasso (Batch GD) with log transform:
Тренировочные данные: MAE=825.4772, RMSE=1239.0650, R²=0.3893
Тестовые данные:     MAE=827.5148, RMSE=1237.1942, R²=0.3818

In [246]:
# БЛОК 2: Удаление выбросов только из обучающей выборки + логарифмирование
print("\n" + "="*50)
print("2. УДАЛЕНИЕ ВЫБРОСОВ ИЗ ОБУЧАЮЩЕЙ ВЫБОРКИ + ЛОГАРИФМИРОВАНИЕ")
print("="*50)

# Создаем копии данных для очистки
X_train_clean = X_train.copy()
y_train_clean = y_train.copy()
X_test_clean = X_test.copy()
y_test_clean = y_test.copy()

def remove_outliers_iqr(X, y):
    Q1 = y.quantile(0.25)
    Q3 = y.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    mask = (y >= lower_bound) & (y <= upper_bound)
    return X[mask], y[mask]

# Удаляем выбросы только из обучающей выборки
X_train_clean, y_train_clean = remove_outliers_iqr(X_train_clean, y_train_clean)

# Применяем логарифмирование к целевой переменной (только к обучающей)
y_train_clean_log = np.log1p(y_train_clean)

# Нормализуем очищенные данные
my_minmax_scaler_clean = MyMinMaxScaler()
X_train_clean_scaled = my_minmax_scaler_clean.fit_transform(X_train_clean)
X_test_clean_scaled = my_minmax_scaler_clean.transform(X_test_clean)

# Обучаем модель на очищенных данных с логарифмированием
model_lasso_clean = LinearRegression_my(method='Batch_Gradient_Descent', 
                                       lambda1=0.00, lambda2=0.0, 
                                       learning_rate=0.01)
model_lasso_clean.fit(X_train_clean_scaled, y_train_clean_log, epochs=5000)

# Предсказания на тренировочных данных
y_train_pred_log = model_lasso_clean.predict(X_train_clean_scaled)
y_train_pred_log_clipped = np.clip(y_train_pred_log, np.log1p(quanil_1), np.log1p(quanil_99))
y_train_pred = np.expm1(y_train_pred_log_clipped)

# Предсказания на тестовых данных
y_test_pred_log = model_lasso_clean.predict(X_test_clean_scaled)
y_test_pred_log_clipped = np.clip(y_test_pred_log, np.log1p(quanil_1), np.log1p(quanil_99))
y_test_pred = np.expm1(y_test_pred_log_clipped)

# Метрики для тренировочных данных
mae_train_clean = mean_absolute_error(y_train_clean, y_train_pred)
rmse_train_clean = np.sqrt(mean_squared_error(y_train_clean, y_train_pred))
r2_train_clean = r2_score(y_train_clean, y_train_pred)

# Метрики для тестовых данных
mae_test_clean = mean_absolute_error(y_test_clean, y_test_pred)
rmse_test_clean = np.sqrt(mean_squared_error(y_test_clean, y_test_pred))
r2_test_clean = r2_score(y_test_clean, y_test_pred)

print(f"My Lasso (Batch GD) with outliers removal and log transform:")
print(f"Тренировочные данные: MAE={mae_train_clean:.4f}, RMSE={rmse_train_clean:.4f}, R²={r2_train_clean:.4f}")
print(f"Тестовые данные:     MAE={mae_test_clean:.4f}, RMSE={rmse_test_clean:.4f}, R²={r2_test_clean:.4f}")
print(f"Удалено {len(X_train) - len(X_train_clean)} выбросов из обучающих данных")

==================================================
2. УДАЛЕНИЕ ВЫБРОСОВ ИЗ ОБУЧАЮЩЕЙ ВЫБОРКИ + ЛОГАРИФМИРОВАНИЕ
==================================================

100%|██████████████████████████████████████| 5000/5000 [00:21<00:00, 237.30it/s]

My Lasso (Batch GD) with outliers removal and log transform:
Тренировочные данные: MAE=670.1463, RMSE=875.8360, R²=0.3559
Тестовые данные:     MAE=842.3581, RMSE=1289.7902, R²=0.3282
Удалено 2589 выбросов из обучающих данных

In [252]:
# БЛОК 3: Мини-пакетный градиентный спуск
print("\n" + "="*50)
print("3. МИНИ-ПАКЕТНЫЙ ГРАДИЕНТНЫЙ СПУСК")
print("="*50)

# Создаем копии данных для мини-пакетного обучения
X_train_mb = X_train.copy()
y_train_mb = y_train.copy()
X_test_mb = X_test.copy()
y_test_mb = y_test.copy()

# Нормализуем данные
my_minmax_scaler_mb = MyMinMaxScaler()
X_train_mb_scaled = my_minmax_scaler_mb.fit_transform(X_train_mb)
X_test_mb_scaled = my_minmax_scaler_mb.transform(X_test_mb)

# Обучаем модель с мини-пакетным градиентным спуском
model_lasso_minibatch = LinearRegression_my(method='MiniBatch_Gradient_Descent', 
                                          lambda1=0.1, lambda2=0.01, 
                                          batch_size=128, learning_rate=0.01)
model_lasso_minibatch.fit(X_train_mb_scaled, y_train_mb)

# Предсказания на тренировочных данных
y_train_pred_mb = model_lasso_minibatch.predict(X_train_mb_scaled)

# Предсказания на тестовых данных
y_test_pred_mb = model_lasso_minibatch.predict(X_test_mb_scaled)

# Метрики для тренировочных данных
mae_train_mb = mean_absolute_error(y_train_mb, y_train_pred_mb)
rmse_train_mb = np.sqrt(mean_squared_error(y_train_mb, y_train_pred_mb))
r2_train_mb = r2_score(y_train_mb, y_train_pred_mb)

# Метрики для тестовых данных
mae_test_mb = mean_absolute_error(y_test_mb, y_test_pred_mb)
rmse_test_mb = np.sqrt(mean_squared_error(y_test_mb, y_test_pred_mb))
r2_test_mb = r2_score(y_test_mb, y_test_pred_mb)

print(f"My Lasso (MiniBatch GD L1):")
print(f"Тренировочные данные: MAE={mae_train_mb:.4f}, RMSE={rmse_train_mb:.4f}, R²={r2_train_mb:.4f}")
print(f"Тестовые данные:     MAE={mae_test_mb:.4f}, RMSE={rmse_test_mb:.4f}, R²={r2_test_mb:.4f}")

==================================================
3. МИНИ-ПАКЕТНЫЙ ГРАДИЕНТНЫЙ СПУСК
==================================================

100%|███████████████████████████████████████| 1000/1000 [00:27<00:00, 35.72it/s]

My Lasso (MiniBatch GD L1):
Тренировочные данные: MAE=820.6747, RMSE=1191.6924, R²=0.4351
Тестовые данные:     MAE=14602603.0619, RMSE=3950017005.7188, R²=-6301210338925.9346